-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
-- Version: 2021.1
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity LINEAR_ReadFromMem_Pipeline_VITIS_LOOP_168_11_VITIS_LOOP_177_13 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    mul_ln166_1 : IN STD_LOGIC_VECTOR (63 downto 0);
    add_ln168_1 : IN STD_LOGIC_VECTOR (31 downto 0);
    payload254_04 : IN STD_LOGIC_VECTOR (767 downto 0);
    trunc_ln3 : IN STD_LOGIC_VECTOR (10 downto 0);
    iact_buffer_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    iact_buffer_ce0 : OUT STD_LOGIC;
    iact_buffer_we0 : OUT STD_LOGIC;
    iact_buffer_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of LINEAR_ReadFromMem_Pipeline_VITIS_LOOP_168_11_VITIS_LOOP_177_13 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln168_fu_154_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal zext_ln178_fu_274_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal j_2_fu_54 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln177_fu_279_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal i_5_fu_58 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln168_2_fu_225_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal indvar_flatten7_fu_62 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln168_fu_159_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln176_fu_124_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln176_1_fu_136_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln6_fu_128_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal shl_ln176_1_fu_140_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln177_fu_174_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln168_2_fu_168_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln176_2_fu_187_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln176_3_fu_199_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln176_mid1_fu_191_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal shl_ln176_1_mid1_fu_203_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln176_1_fu_211_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln176_fu_148_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln168_fu_179_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln674_fu_237_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_fu_241_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln674_fu_249_p1 : STD_LOGIC_VECTOR (767 downto 0);
    signal lshr_ln674_fu_253_p2 : STD_LOGIC_VECTOR (767 downto 0);
    signal empty_fu_233_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln178_1_fu_263_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln168_1_fu_217_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln178_fu_268_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component LINEAR_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component LINEAR_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    i_5_fu_58_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    i_5_fu_58 <= ap_const_lv32_0;
                elsif (((icmp_ln168_fu_154_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    i_5_fu_58 <= select_ln168_2_fu_225_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten7_fu_62_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten7_fu_62 <= ap_const_lv64_0;
                elsif (((icmp_ln168_fu_154_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    indvar_flatten7_fu_62 <= add_ln168_fu_159_p2;
                end if;
            end if; 
        end if;
    end process;

    j_2_fu_54_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    j_2_fu_54 <= ap_const_lv32_0;
                elsif (((icmp_ln168_fu_154_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    j_2_fu_54 <= add_ln177_fu_279_p2;
                end if;
            end if; 
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln168_2_fu_168_p2 <= std_logic_vector(unsigned(i_5_fu_58) + unsigned(ap_const_lv32_1));
    add_ln168_fu_159_p2 <= std_logic_vector(unsigned(indvar_flatten7_fu_62) + unsigned(ap_const_lv64_1));
    add_ln177_fu_279_p2 <= std_logic_vector(unsigned(select_ln168_fu_179_p3) + unsigned(ap_const_lv32_1));
    add_ln178_1_fu_263_p2 <= std_logic_vector(unsigned(trunc_ln3) + unsigned(empty_fu_233_p1));
    add_ln178_fu_268_p2 <= std_logic_vector(unsigned(add_ln178_1_fu_263_p2) + unsigned(select_ln168_1_fu_217_p3));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln168_fu_154_p2)
    begin
        if (((icmp_ln168_fu_154_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    empty_fu_233_p1 <= select_ln168_fu_179_p3(11 - 1 downto 0);
    iact_buffer_address0 <= zext_ln178_fu_274_p1(11 - 1 downto 0);

    iact_buffer_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            iact_buffer_ce0 <= ap_const_logic_1;
        else 
            iact_buffer_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    iact_buffer_d0 <= lshr_ln674_fu_253_p2(32 - 1 downto 0);

    iact_buffer_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln168_fu_154_p2, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln168_fu_154_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            iact_buffer_we0 <= ap_const_logic_1;
        else 
            iact_buffer_we0 <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln168_fu_154_p2 <= "1" when (indvar_flatten7_fu_62 = mul_ln166_1) else "0";
    icmp_ln177_fu_174_p2 <= "1" when (j_2_fu_54 = add_ln168_1) else "0";
    lshr_ln674_fu_253_p2 <= std_logic_vector(shift_right(unsigned(payload254_04),to_integer(unsigned('0' & zext_ln674_fu_249_p1(31-1 downto 0)))));
    select_ln168_1_fu_217_p3 <= 
        sub_ln176_1_fu_211_p2 when (icmp_ln177_fu_174_p2(0) = '1') else 
        sub_ln176_fu_148_p2;
    select_ln168_2_fu_225_p3 <= 
        add_ln168_2_fu_168_p2 when (icmp_ln177_fu_174_p2(0) = '1') else 
        i_5_fu_58;
    select_ln168_fu_179_p3 <= 
        ap_const_lv32_0 when (icmp_ln177_fu_174_p2(0) = '1') else 
        j_2_fu_54;
    shl_ln176_1_fu_140_p3 <= (trunc_ln176_1_fu_136_p1 & ap_const_lv3_0);
    shl_ln176_1_mid1_fu_203_p3 <= (trunc_ln176_3_fu_199_p1 & ap_const_lv3_0);
    shl_ln176_mid1_fu_191_p3 <= (trunc_ln176_2_fu_187_p1 & ap_const_lv5_0);
    shl_ln6_fu_128_p3 <= (trunc_ln176_fu_124_p1 & ap_const_lv5_0);
    sub_ln176_1_fu_211_p2 <= std_logic_vector(unsigned(shl_ln176_mid1_fu_191_p3) - unsigned(shl_ln176_1_mid1_fu_203_p3));
    sub_ln176_fu_148_p2 <= std_logic_vector(unsigned(shl_ln6_fu_128_p3) - unsigned(shl_ln176_1_fu_140_p3));
    tmp_fu_241_p3 <= (trunc_ln674_fu_237_p1 & ap_const_lv5_0);
    trunc_ln176_1_fu_136_p1 <= i_5_fu_58(8 - 1 downto 0);
    trunc_ln176_2_fu_187_p1 <= add_ln168_2_fu_168_p2(6 - 1 downto 0);
    trunc_ln176_3_fu_199_p1 <= add_ln168_2_fu_168_p2(8 - 1 downto 0);
    trunc_ln176_fu_124_p1 <= i_5_fu_58(6 - 1 downto 0);
    trunc_ln674_fu_237_p1 <= select_ln168_fu_179_p3(5 - 1 downto 0);
    zext_ln178_fu_274_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln178_fu_268_p2),64));
    zext_ln674_fu_249_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_241_p3),768));
end behav;
