-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
-- Version: 2021.1
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity LINEAR_RunDataFlow is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (27 downto 0);
    p_read1 : IN STD_LOGIC_VECTOR (27 downto 0);
    iacts_stream_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    iacts_stream_empty_n : IN STD_LOGIC;
    iacts_stream_read : OUT STD_LOGIC;
    weights_stream_V_V_0_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_stream_V_V_0_empty_n : IN STD_LOGIC;
    weights_stream_V_V_0_read : OUT STD_LOGIC;
    weights_stream_V_V_1_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_stream_V_V_1_empty_n : IN STD_LOGIC;
    weights_stream_V_V_1_read : OUT STD_LOGIC;
    weights_stream_V_V_2_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_stream_V_V_2_empty_n : IN STD_LOGIC;
    weights_stream_V_V_2_read : OUT STD_LOGIC;
    weights_stream_V_V_3_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_stream_V_V_3_empty_n : IN STD_LOGIC;
    weights_stream_V_V_3_read : OUT STD_LOGIC;
    weights_stream_V_V_4_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_stream_V_V_4_empty_n : IN STD_LOGIC;
    weights_stream_V_V_4_read : OUT STD_LOGIC;
    weights_stream_V_V_5_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_stream_V_V_5_empty_n : IN STD_LOGIC;
    weights_stream_V_V_5_read : OUT STD_LOGIC;
    weights_stream_V_V_6_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_stream_V_V_6_empty_n : IN STD_LOGIC;
    weights_stream_V_V_6_read : OUT STD_LOGIC;
    weights_stream_V_V_7_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_stream_V_V_7_empty_n : IN STD_LOGIC;
    weights_stream_V_V_7_read : OUT STD_LOGIC;
    weights_stream_V_V_8_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_stream_V_V_8_empty_n : IN STD_LOGIC;
    weights_stream_V_V_8_read : OUT STD_LOGIC;
    weights_stream_V_V_9_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_stream_V_V_9_empty_n : IN STD_LOGIC;
    weights_stream_V_V_9_read : OUT STD_LOGIC;
    weights_stream_V_V_10_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_stream_V_V_10_empty_n : IN STD_LOGIC;
    weights_stream_V_V_10_read : OUT STD_LOGIC;
    weights_stream_V_V_11_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_stream_V_V_11_empty_n : IN STD_LOGIC;
    weights_stream_V_V_11_read : OUT STD_LOGIC;
    weights_stream_V_V_12_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_stream_V_V_12_empty_n : IN STD_LOGIC;
    weights_stream_V_V_12_read : OUT STD_LOGIC;
    weights_stream_V_V_13_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_stream_V_V_13_empty_n : IN STD_LOGIC;
    weights_stream_V_V_13_read : OUT STD_LOGIC;
    weights_stream_V_V_14_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_stream_V_V_14_empty_n : IN STD_LOGIC;
    weights_stream_V_V_14_read : OUT STD_LOGIC;
    weights_stream_V_V_15_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_stream_V_V_15_empty_n : IN STD_LOGIC;
    weights_stream_V_V_15_read : OUT STD_LOGIC;
    weights_stream_V_V_16_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_stream_V_V_16_empty_n : IN STD_LOGIC;
    weights_stream_V_V_16_read : OUT STD_LOGIC;
    weights_stream_V_V_17_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_stream_V_V_17_empty_n : IN STD_LOGIC;
    weights_stream_V_V_17_read : OUT STD_LOGIC;
    weights_stream_V_V_18_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_stream_V_V_18_empty_n : IN STD_LOGIC;
    weights_stream_V_V_18_read : OUT STD_LOGIC;
    weights_stream_V_V_19_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_stream_V_V_19_empty_n : IN STD_LOGIC;
    weights_stream_V_V_19_read : OUT STD_LOGIC;
    weights_stream_V_V_20_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_stream_V_V_20_empty_n : IN STD_LOGIC;
    weights_stream_V_V_20_read : OUT STD_LOGIC;
    weights_stream_V_V_21_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_stream_V_V_21_empty_n : IN STD_LOGIC;
    weights_stream_V_V_21_read : OUT STD_LOGIC;
    weights_stream_V_V_22_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_stream_V_V_22_empty_n : IN STD_LOGIC;
    weights_stream_V_V_22_read : OUT STD_LOGIC;
    weights_stream_V_V_23_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_stream_V_V_23_empty_n : IN STD_LOGIC;
    weights_stream_V_V_23_read : OUT STD_LOGIC;
    weights_stream_V_V_24_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_stream_V_V_24_empty_n : IN STD_LOGIC;
    weights_stream_V_V_24_read : OUT STD_LOGIC;
    weights_stream_V_V_25_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_stream_V_V_25_empty_n : IN STD_LOGIC;
    weights_stream_V_V_25_read : OUT STD_LOGIC;
    weights_stream_V_V_26_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_stream_V_V_26_empty_n : IN STD_LOGIC;
    weights_stream_V_V_26_read : OUT STD_LOGIC;
    weights_stream_V_V_27_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_stream_V_V_27_empty_n : IN STD_LOGIC;
    weights_stream_V_V_27_read : OUT STD_LOGIC;
    weights_stream_V_V_28_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_stream_V_V_28_empty_n : IN STD_LOGIC;
    weights_stream_V_V_28_read : OUT STD_LOGIC;
    weights_stream_V_V_29_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_stream_V_V_29_empty_n : IN STD_LOGIC;
    weights_stream_V_V_29_read : OUT STD_LOGIC;
    weights_stream_V_V_30_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_stream_V_V_30_empty_n : IN STD_LOGIC;
    weights_stream_V_V_30_read : OUT STD_LOGIC;
    weights_stream_V_V_31_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_stream_V_V_31_empty_n : IN STD_LOGIC;
    weights_stream_V_V_31_read : OUT STD_LOGIC;
    output_buf_V_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    output_buf_V_ce0 : OUT STD_LOGIC;
    output_buf_V_we0 : OUT STD_LOGIC;
    output_buf_V_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    output_buf_V_q0 : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of LINEAR_RunDataFlow is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv27_0 : STD_LOGIC_VECTOR (26 downto 0) := "000000000000000000000000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant ap_const_lv27_1 : STD_LOGIC_VECTOR (26 downto 0) := "000000000000000000000000001";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal block_num_y_cast_i_fu_271_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal block_num_y_cast_i_reg_387 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_i_fu_285_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_i_reg_392 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_2_reg_400 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal add_ln352_fu_297_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln352_reg_405 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_3_fu_311_p2 : STD_LOGIC_VECTOR (26 downto 0);
    signal i_3_reg_413 : STD_LOGIC_VECTOR (26 downto 0);
    signal trunc_ln357_fu_325_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln357_reg_418 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal j_1_fu_335_p2 : STD_LOGIC_VECTOR (26 downto 0);
    signal j_1_reg_426 : STD_LOGIC_VECTOR (26 downto 0);
    signal trunc_ln358_fu_346_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln358_reg_431 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln357_fu_330_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln359_fu_350_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln359_reg_435 : STD_LOGIC_VECTOR (0 downto 0);
    signal IACT_TEMP_BUFFER_V_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal IACT_TEMP_BUFFER_V_ce0 : STD_LOGIC;
    signal IACT_TEMP_BUFFER_V_we0 : STD_LOGIC;
    signal IACT_TEMP_BUFFER_V_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal first_processing_buffer_V_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal first_processing_buffer_V_ce0 : STD_LOGIC;
    signal first_processing_buffer_V_we0 : STD_LOGIC;
    signal first_processing_buffer_V_q0 : STD_LOGIC_VECTOR (639 downto 0);
    signal second_processing_buffer_V_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal second_processing_buffer_V_ce0 : STD_LOGIC;
    signal second_processing_buffer_V_we0 : STD_LOGIC;
    signal second_processing_buffer_V_q0 : STD_LOGIC_VECTOR (639 downto 0);
    signal first_bit_buffer_weights_V_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal first_bit_buffer_weights_V_ce0 : STD_LOGIC;
    signal first_bit_buffer_weights_V_we0 : STD_LOGIC;
    signal first_bit_buffer_weights_V_q0 : STD_LOGIC_VECTOR (19 downto 0);
    signal second_bit_buffer_weights_V_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal second_bit_buffer_weights_V_ce0 : STD_LOGIC;
    signal second_bit_buffer_weights_V_we0 : STD_LOGIC;
    signal second_bit_buffer_weights_V_q0 : STD_LOGIC_VECTOR (19 downto 0);
    signal grp_CreateBitMask_fu_171_ap_start : STD_LOGIC;
    signal grp_CreateBitMask_fu_171_ap_done : STD_LOGIC;
    signal grp_CreateBitMask_fu_171_ap_idle : STD_LOGIC;
    signal grp_CreateBitMask_fu_171_ap_ready : STD_LOGIC;
    signal grp_CreateBitMask_fu_171_weights_stream_0_0_0_0_read : STD_LOGIC;
    signal grp_CreateBitMask_fu_171_weights_stream_0_0_0_01_read : STD_LOGIC;
    signal grp_CreateBitMask_fu_171_weights_stream_0_0_0_02_read : STD_LOGIC;
    signal grp_CreateBitMask_fu_171_weights_stream_0_0_0_03_read : STD_LOGIC;
    signal grp_CreateBitMask_fu_171_weights_stream_0_0_0_04_read : STD_LOGIC;
    signal grp_CreateBitMask_fu_171_weights_stream_0_0_0_05_read : STD_LOGIC;
    signal grp_CreateBitMask_fu_171_weights_stream_0_0_0_06_read : STD_LOGIC;
    signal grp_CreateBitMask_fu_171_weights_stream_0_0_0_07_read : STD_LOGIC;
    signal grp_CreateBitMask_fu_171_weights_stream_0_0_0_08_read : STD_LOGIC;
    signal grp_CreateBitMask_fu_171_weights_stream_0_0_0_09_read : STD_LOGIC;
    signal grp_CreateBitMask_fu_171_weights_stream_0_0_0_010_read : STD_LOGIC;
    signal grp_CreateBitMask_fu_171_weights_stream_0_0_0_011_read : STD_LOGIC;
    signal grp_CreateBitMask_fu_171_weights_stream_0_0_0_012_read : STD_LOGIC;
    signal grp_CreateBitMask_fu_171_weights_stream_0_0_0_013_read : STD_LOGIC;
    signal grp_CreateBitMask_fu_171_weights_stream_0_0_0_014_read : STD_LOGIC;
    signal grp_CreateBitMask_fu_171_weights_stream_0_0_0_015_read : STD_LOGIC;
    signal grp_CreateBitMask_fu_171_weights_stream_0_0_0_016_read : STD_LOGIC;
    signal grp_CreateBitMask_fu_171_weights_stream_0_0_0_017_read : STD_LOGIC;
    signal grp_CreateBitMask_fu_171_weights_stream_0_0_0_018_read : STD_LOGIC;
    signal grp_CreateBitMask_fu_171_weights_stream_0_0_0_019_read : STD_LOGIC;
    signal grp_CreateBitMask_fu_171_weights_stream_0_0_0_020_read : STD_LOGIC;
    signal grp_CreateBitMask_fu_171_weights_stream_0_0_0_021_read : STD_LOGIC;
    signal grp_CreateBitMask_fu_171_weights_stream_0_0_0_022_read : STD_LOGIC;
    signal grp_CreateBitMask_fu_171_weights_stream_0_0_0_023_read : STD_LOGIC;
    signal grp_CreateBitMask_fu_171_weights_stream_0_0_0_024_read : STD_LOGIC;
    signal grp_CreateBitMask_fu_171_weights_stream_0_0_0_025_read : STD_LOGIC;
    signal grp_CreateBitMask_fu_171_weights_stream_0_0_0_026_read : STD_LOGIC;
    signal grp_CreateBitMask_fu_171_weights_stream_0_0_0_027_read : STD_LOGIC;
    signal grp_CreateBitMask_fu_171_weights_stream_0_0_0_028_read : STD_LOGIC;
    signal grp_CreateBitMask_fu_171_weights_stream_0_0_0_029_read : STD_LOGIC;
    signal grp_CreateBitMask_fu_171_weights_stream_0_0_0_030_read : STD_LOGIC;
    signal grp_CreateBitMask_fu_171_weights_stream_0_0_0_031_read : STD_LOGIC;
    signal grp_CreateBitMask_fu_171_processing_buffer_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_CreateBitMask_fu_171_processing_buffer_ce0 : STD_LOGIC;
    signal grp_CreateBitMask_fu_171_processing_buffer_we0 : STD_LOGIC;
    signal grp_CreateBitMask_fu_171_processing_buffer_d0 : STD_LOGIC_VECTOR (639 downto 0);
    signal grp_CreateBitMask_fu_171_bit_buffer_weights_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_CreateBitMask_fu_171_bit_buffer_weights_ce0 : STD_LOGIC;
    signal grp_CreateBitMask_fu_171_bit_buffer_weights_we0 : STD_LOGIC;
    signal grp_CreateBitMask_fu_171_bit_buffer_weights_d0 : STD_LOGIC_VECTOR (19 downto 0);
    signal grp_RunDataFlow_Pipeline_VITIS_LOOP_341_1_fu_243_ap_start : STD_LOGIC;
    signal grp_RunDataFlow_Pipeline_VITIS_LOOP_341_1_fu_243_ap_done : STD_LOGIC;
    signal grp_RunDataFlow_Pipeline_VITIS_LOOP_341_1_fu_243_ap_idle : STD_LOGIC;
    signal grp_RunDataFlow_Pipeline_VITIS_LOOP_341_1_fu_243_ap_ready : STD_LOGIC;
    signal grp_RunDataFlow_Pipeline_VITIS_LOOP_341_1_fu_243_iacts_stream_read : STD_LOGIC;
    signal grp_RunDataFlow_Pipeline_VITIS_LOOP_341_1_fu_243_IACT_TEMP_BUFFER_V_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_RunDataFlow_Pipeline_VITIS_LOOP_341_1_fu_243_IACT_TEMP_BUFFER_V_ce0 : STD_LOGIC;
    signal grp_RunDataFlow_Pipeline_VITIS_LOOP_341_1_fu_243_IACT_TEMP_BUFFER_V_we0 : STD_LOGIC;
    signal grp_RunDataFlow_Pipeline_VITIS_LOOP_341_1_fu_243_IACT_TEMP_BUFFER_V_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_DPEComputation_fu_250_ap_start : STD_LOGIC;
    signal grp_DPEComputation_fu_250_ap_done : STD_LOGIC;
    signal grp_DPEComputation_fu_250_ap_idle : STD_LOGIC;
    signal grp_DPEComputation_fu_250_ap_ready : STD_LOGIC;
    signal grp_DPEComputation_fu_250_IACT_TEMP_BUFFER_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_DPEComputation_fu_250_IACT_TEMP_BUFFER_ce0 : STD_LOGIC;
    signal grp_DPEComputation_fu_250_processing_buffer_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_DPEComputation_fu_250_processing_buffer_ce0 : STD_LOGIC;
    signal grp_DPEComputation_fu_250_processing_buffer_q0 : STD_LOGIC_VECTOR (639 downto 0);
    signal grp_DPEComputation_fu_250_bit_buffer_weights_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_DPEComputation_fu_250_bit_buffer_weights_ce0 : STD_LOGIC;
    signal grp_DPEComputation_fu_250_bit_buffer_weights_q0 : STD_LOGIC_VECTOR (19 downto 0);
    signal grp_DPEComputation_fu_250_buffer_out_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DPEComputation_fu_250_buffer_out_ce0 : STD_LOGIC;
    signal grp_DPEComputation_fu_250_buffer_out_we0 : STD_LOGIC;
    signal grp_DPEComputation_fu_250_buffer_out_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal j_reg_160 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_predicate_op96_call_state6 : BOOLEAN;
    signal ap_predicate_op97_call_state6 : BOOLEAN;
    signal ap_predicate_op99_call_state6 : BOOLEAN;
    signal ap_predicate_op100_call_state6 : BOOLEAN;
    signal ap_block_state6_on_subcall_done : BOOLEAN;
    signal grp_CreateBitMask_fu_171_ap_start_reg : STD_LOGIC := '0';
    signal ap_block_state1_ignore_call48 : BOOLEAN;
    signal grp_RunDataFlow_Pipeline_VITIS_LOOP_341_1_fu_243_ap_start_reg : STD_LOGIC := '0';
    signal icmp_ln352_fu_306_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_DPEComputation_fu_250_ap_start_reg : STD_LOGIC := '0';
    signal phi_mul_fu_120 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal i_fu_124 : STD_LOGIC_VECTOR (26 downto 0);
    signal block_num_y_cast_i_fu_271_p0 : STD_LOGIC_VECTOR (27 downto 0);
    signal mul2_i_fu_279_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln352_fu_302_p1 : STD_LOGIC_VECTOR (27 downto 0);
    signal icmp_ln352_fu_306_p1 : STD_LOGIC_VECTOR (27 downto 0);
    signal zext_ln357_1_fu_321_p1 : STD_LOGIC_VECTOR (27 downto 0);
    signal icmp_ln357_fu_330_p1 : STD_LOGIC_VECTOR (27 downto 0);
    signal zext_ln357_fu_317_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal batch_fu_341_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component LINEAR_CreateBitMask IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        weights_stream_0_0_0_0_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_stream_0_0_0_0_empty_n : IN STD_LOGIC;
        weights_stream_0_0_0_0_read : OUT STD_LOGIC;
        weights_stream_0_0_0_01_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_stream_0_0_0_01_empty_n : IN STD_LOGIC;
        weights_stream_0_0_0_01_read : OUT STD_LOGIC;
        weights_stream_0_0_0_02_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_stream_0_0_0_02_empty_n : IN STD_LOGIC;
        weights_stream_0_0_0_02_read : OUT STD_LOGIC;
        weights_stream_0_0_0_03_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_stream_0_0_0_03_empty_n : IN STD_LOGIC;
        weights_stream_0_0_0_03_read : OUT STD_LOGIC;
        weights_stream_0_0_0_04_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_stream_0_0_0_04_empty_n : IN STD_LOGIC;
        weights_stream_0_0_0_04_read : OUT STD_LOGIC;
        weights_stream_0_0_0_05_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_stream_0_0_0_05_empty_n : IN STD_LOGIC;
        weights_stream_0_0_0_05_read : OUT STD_LOGIC;
        weights_stream_0_0_0_06_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_stream_0_0_0_06_empty_n : IN STD_LOGIC;
        weights_stream_0_0_0_06_read : OUT STD_LOGIC;
        weights_stream_0_0_0_07_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_stream_0_0_0_07_empty_n : IN STD_LOGIC;
        weights_stream_0_0_0_07_read : OUT STD_LOGIC;
        weights_stream_0_0_0_08_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_stream_0_0_0_08_empty_n : IN STD_LOGIC;
        weights_stream_0_0_0_08_read : OUT STD_LOGIC;
        weights_stream_0_0_0_09_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_stream_0_0_0_09_empty_n : IN STD_LOGIC;
        weights_stream_0_0_0_09_read : OUT STD_LOGIC;
        weights_stream_0_0_0_010_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_stream_0_0_0_010_empty_n : IN STD_LOGIC;
        weights_stream_0_0_0_010_read : OUT STD_LOGIC;
        weights_stream_0_0_0_011_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_stream_0_0_0_011_empty_n : IN STD_LOGIC;
        weights_stream_0_0_0_011_read : OUT STD_LOGIC;
        weights_stream_0_0_0_012_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_stream_0_0_0_012_empty_n : IN STD_LOGIC;
        weights_stream_0_0_0_012_read : OUT STD_LOGIC;
        weights_stream_0_0_0_013_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_stream_0_0_0_013_empty_n : IN STD_LOGIC;
        weights_stream_0_0_0_013_read : OUT STD_LOGIC;
        weights_stream_0_0_0_014_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_stream_0_0_0_014_empty_n : IN STD_LOGIC;
        weights_stream_0_0_0_014_read : OUT STD_LOGIC;
        weights_stream_0_0_0_015_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_stream_0_0_0_015_empty_n : IN STD_LOGIC;
        weights_stream_0_0_0_015_read : OUT STD_LOGIC;
        weights_stream_0_0_0_016_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_stream_0_0_0_016_empty_n : IN STD_LOGIC;
        weights_stream_0_0_0_016_read : OUT STD_LOGIC;
        weights_stream_0_0_0_017_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_stream_0_0_0_017_empty_n : IN STD_LOGIC;
        weights_stream_0_0_0_017_read : OUT STD_LOGIC;
        weights_stream_0_0_0_018_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_stream_0_0_0_018_empty_n : IN STD_LOGIC;
        weights_stream_0_0_0_018_read : OUT STD_LOGIC;
        weights_stream_0_0_0_019_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_stream_0_0_0_019_empty_n : IN STD_LOGIC;
        weights_stream_0_0_0_019_read : OUT STD_LOGIC;
        weights_stream_0_0_0_020_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_stream_0_0_0_020_empty_n : IN STD_LOGIC;
        weights_stream_0_0_0_020_read : OUT STD_LOGIC;
        weights_stream_0_0_0_021_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_stream_0_0_0_021_empty_n : IN STD_LOGIC;
        weights_stream_0_0_0_021_read : OUT STD_LOGIC;
        weights_stream_0_0_0_022_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_stream_0_0_0_022_empty_n : IN STD_LOGIC;
        weights_stream_0_0_0_022_read : OUT STD_LOGIC;
        weights_stream_0_0_0_023_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_stream_0_0_0_023_empty_n : IN STD_LOGIC;
        weights_stream_0_0_0_023_read : OUT STD_LOGIC;
        weights_stream_0_0_0_024_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_stream_0_0_0_024_empty_n : IN STD_LOGIC;
        weights_stream_0_0_0_024_read : OUT STD_LOGIC;
        weights_stream_0_0_0_025_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_stream_0_0_0_025_empty_n : IN STD_LOGIC;
        weights_stream_0_0_0_025_read : OUT STD_LOGIC;
        weights_stream_0_0_0_026_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_stream_0_0_0_026_empty_n : IN STD_LOGIC;
        weights_stream_0_0_0_026_read : OUT STD_LOGIC;
        weights_stream_0_0_0_027_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_stream_0_0_0_027_empty_n : IN STD_LOGIC;
        weights_stream_0_0_0_027_read : OUT STD_LOGIC;
        weights_stream_0_0_0_028_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_stream_0_0_0_028_empty_n : IN STD_LOGIC;
        weights_stream_0_0_0_028_read : OUT STD_LOGIC;
        weights_stream_0_0_0_029_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_stream_0_0_0_029_empty_n : IN STD_LOGIC;
        weights_stream_0_0_0_029_read : OUT STD_LOGIC;
        weights_stream_0_0_0_030_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_stream_0_0_0_030_empty_n : IN STD_LOGIC;
        weights_stream_0_0_0_030_read : OUT STD_LOGIC;
        weights_stream_0_0_0_031_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_stream_0_0_0_031_empty_n : IN STD_LOGIC;
        weights_stream_0_0_0_031_read : OUT STD_LOGIC;
        processing_buffer_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        processing_buffer_ce0 : OUT STD_LOGIC;
        processing_buffer_we0 : OUT STD_LOGIC;
        processing_buffer_d0 : OUT STD_LOGIC_VECTOR (639 downto 0);
        bit_buffer_weights_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        bit_buffer_weights_ce0 : OUT STD_LOGIC;
        bit_buffer_weights_we0 : OUT STD_LOGIC;
        bit_buffer_weights_d0 : OUT STD_LOGIC_VECTOR (19 downto 0) );
    end component;


    component LINEAR_RunDataFlow_Pipeline_VITIS_LOOP_341_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        iacts_stream_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        iacts_stream_empty_n : IN STD_LOGIC;
        iacts_stream_read : OUT STD_LOGIC;
        IACT_TEMP_BUFFER_V_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        IACT_TEMP_BUFFER_V_ce0 : OUT STD_LOGIC;
        IACT_TEMP_BUFFER_V_we0 : OUT STD_LOGIC;
        IACT_TEMP_BUFFER_V_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component LINEAR_DPEComputation IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        IACT_TEMP_BUFFER_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        IACT_TEMP_BUFFER_ce0 : OUT STD_LOGIC;
        IACT_TEMP_BUFFER_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        block_idx_x : IN STD_LOGIC_VECTOR (26 downto 0);
        block_idx_y : IN STD_LOGIC_VECTOR (5 downto 0);
        processing_buffer_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        processing_buffer_ce0 : OUT STD_LOGIC;
        processing_buffer_q0 : IN STD_LOGIC_VECTOR (639 downto 0);
        bit_buffer_weights_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        bit_buffer_weights_ce0 : OUT STD_LOGIC;
        bit_buffer_weights_q0 : IN STD_LOGIC_VECTOR (19 downto 0);
        buffer_out_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        buffer_out_ce0 : OUT STD_LOGIC;
        buffer_out_we0 : OUT STD_LOGIC;
        buffer_out_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        buffer_out_q0 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component LINEAR_mul_28s_28s_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (27 downto 0);
        din1 : IN STD_LOGIC_VECTOR (27 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component LINEAR_RunDataFlow_IACT_TEMP_BUFFER_V IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component LINEAR_RunDataFlow_first_processing_buffer_V IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (639 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (639 downto 0) );
    end component;


    component LINEAR_RunDataFlow_first_bit_buffer_weights_V IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (19 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (19 downto 0) );
    end component;



begin
    IACT_TEMP_BUFFER_V_U : component LINEAR_RunDataFlow_IACT_TEMP_BUFFER_V
    generic map (
        DataWidth => 32,
        AddressRange => 32,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => IACT_TEMP_BUFFER_V_address0,
        ce0 => IACT_TEMP_BUFFER_V_ce0,
        we0 => IACT_TEMP_BUFFER_V_we0,
        d0 => grp_RunDataFlow_Pipeline_VITIS_LOOP_341_1_fu_243_IACT_TEMP_BUFFER_V_d0,
        q0 => IACT_TEMP_BUFFER_V_q0);

    first_processing_buffer_V_U : component LINEAR_RunDataFlow_first_processing_buffer_V
    generic map (
        DataWidth => 640,
        AddressRange => 32,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => first_processing_buffer_V_address0,
        ce0 => first_processing_buffer_V_ce0,
        we0 => first_processing_buffer_V_we0,
        d0 => grp_CreateBitMask_fu_171_processing_buffer_d0,
        q0 => first_processing_buffer_V_q0);

    second_processing_buffer_V_U : component LINEAR_RunDataFlow_first_processing_buffer_V
    generic map (
        DataWidth => 640,
        AddressRange => 32,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => second_processing_buffer_V_address0,
        ce0 => second_processing_buffer_V_ce0,
        we0 => second_processing_buffer_V_we0,
        d0 => grp_CreateBitMask_fu_171_processing_buffer_d0,
        q0 => second_processing_buffer_V_q0);

    first_bit_buffer_weights_V_U : component LINEAR_RunDataFlow_first_bit_buffer_weights_V
    generic map (
        DataWidth => 20,
        AddressRange => 32,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => first_bit_buffer_weights_V_address0,
        ce0 => first_bit_buffer_weights_V_ce0,
        we0 => first_bit_buffer_weights_V_we0,
        d0 => grp_CreateBitMask_fu_171_bit_buffer_weights_d0,
        q0 => first_bit_buffer_weights_V_q0);

    second_bit_buffer_weights_V_U : component LINEAR_RunDataFlow_first_bit_buffer_weights_V
    generic map (
        DataWidth => 20,
        AddressRange => 32,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => second_bit_buffer_weights_V_address0,
        ce0 => second_bit_buffer_weights_V_ce0,
        we0 => second_bit_buffer_weights_V_we0,
        d0 => grp_CreateBitMask_fu_171_bit_buffer_weights_d0,
        q0 => second_bit_buffer_weights_V_q0);

    grp_CreateBitMask_fu_171 : component LINEAR_CreateBitMask
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_CreateBitMask_fu_171_ap_start,
        ap_done => grp_CreateBitMask_fu_171_ap_done,
        ap_idle => grp_CreateBitMask_fu_171_ap_idle,
        ap_ready => grp_CreateBitMask_fu_171_ap_ready,
        weights_stream_0_0_0_0_dout => weights_stream_V_V_0_dout,
        weights_stream_0_0_0_0_empty_n => weights_stream_V_V_0_empty_n,
        weights_stream_0_0_0_0_read => grp_CreateBitMask_fu_171_weights_stream_0_0_0_0_read,
        weights_stream_0_0_0_01_dout => weights_stream_V_V_1_dout,
        weights_stream_0_0_0_01_empty_n => weights_stream_V_V_1_empty_n,
        weights_stream_0_0_0_01_read => grp_CreateBitMask_fu_171_weights_stream_0_0_0_01_read,
        weights_stream_0_0_0_02_dout => weights_stream_V_V_2_dout,
        weights_stream_0_0_0_02_empty_n => weights_stream_V_V_2_empty_n,
        weights_stream_0_0_0_02_read => grp_CreateBitMask_fu_171_weights_stream_0_0_0_02_read,
        weights_stream_0_0_0_03_dout => weights_stream_V_V_3_dout,
        weights_stream_0_0_0_03_empty_n => weights_stream_V_V_3_empty_n,
        weights_stream_0_0_0_03_read => grp_CreateBitMask_fu_171_weights_stream_0_0_0_03_read,
        weights_stream_0_0_0_04_dout => weights_stream_V_V_4_dout,
        weights_stream_0_0_0_04_empty_n => weights_stream_V_V_4_empty_n,
        weights_stream_0_0_0_04_read => grp_CreateBitMask_fu_171_weights_stream_0_0_0_04_read,
        weights_stream_0_0_0_05_dout => weights_stream_V_V_5_dout,
        weights_stream_0_0_0_05_empty_n => weights_stream_V_V_5_empty_n,
        weights_stream_0_0_0_05_read => grp_CreateBitMask_fu_171_weights_stream_0_0_0_05_read,
        weights_stream_0_0_0_06_dout => weights_stream_V_V_6_dout,
        weights_stream_0_0_0_06_empty_n => weights_stream_V_V_6_empty_n,
        weights_stream_0_0_0_06_read => grp_CreateBitMask_fu_171_weights_stream_0_0_0_06_read,
        weights_stream_0_0_0_07_dout => weights_stream_V_V_7_dout,
        weights_stream_0_0_0_07_empty_n => weights_stream_V_V_7_empty_n,
        weights_stream_0_0_0_07_read => grp_CreateBitMask_fu_171_weights_stream_0_0_0_07_read,
        weights_stream_0_0_0_08_dout => weights_stream_V_V_8_dout,
        weights_stream_0_0_0_08_empty_n => weights_stream_V_V_8_empty_n,
        weights_stream_0_0_0_08_read => grp_CreateBitMask_fu_171_weights_stream_0_0_0_08_read,
        weights_stream_0_0_0_09_dout => weights_stream_V_V_9_dout,
        weights_stream_0_0_0_09_empty_n => weights_stream_V_V_9_empty_n,
        weights_stream_0_0_0_09_read => grp_CreateBitMask_fu_171_weights_stream_0_0_0_09_read,
        weights_stream_0_0_0_010_dout => weights_stream_V_V_10_dout,
        weights_stream_0_0_0_010_empty_n => weights_stream_V_V_10_empty_n,
        weights_stream_0_0_0_010_read => grp_CreateBitMask_fu_171_weights_stream_0_0_0_010_read,
        weights_stream_0_0_0_011_dout => weights_stream_V_V_11_dout,
        weights_stream_0_0_0_011_empty_n => weights_stream_V_V_11_empty_n,
        weights_stream_0_0_0_011_read => grp_CreateBitMask_fu_171_weights_stream_0_0_0_011_read,
        weights_stream_0_0_0_012_dout => weights_stream_V_V_12_dout,
        weights_stream_0_0_0_012_empty_n => weights_stream_V_V_12_empty_n,
        weights_stream_0_0_0_012_read => grp_CreateBitMask_fu_171_weights_stream_0_0_0_012_read,
        weights_stream_0_0_0_013_dout => weights_stream_V_V_13_dout,
        weights_stream_0_0_0_013_empty_n => weights_stream_V_V_13_empty_n,
        weights_stream_0_0_0_013_read => grp_CreateBitMask_fu_171_weights_stream_0_0_0_013_read,
        weights_stream_0_0_0_014_dout => weights_stream_V_V_14_dout,
        weights_stream_0_0_0_014_empty_n => weights_stream_V_V_14_empty_n,
        weights_stream_0_0_0_014_read => grp_CreateBitMask_fu_171_weights_stream_0_0_0_014_read,
        weights_stream_0_0_0_015_dout => weights_stream_V_V_15_dout,
        weights_stream_0_0_0_015_empty_n => weights_stream_V_V_15_empty_n,
        weights_stream_0_0_0_015_read => grp_CreateBitMask_fu_171_weights_stream_0_0_0_015_read,
        weights_stream_0_0_0_016_dout => weights_stream_V_V_16_dout,
        weights_stream_0_0_0_016_empty_n => weights_stream_V_V_16_empty_n,
        weights_stream_0_0_0_016_read => grp_CreateBitMask_fu_171_weights_stream_0_0_0_016_read,
        weights_stream_0_0_0_017_dout => weights_stream_V_V_17_dout,
        weights_stream_0_0_0_017_empty_n => weights_stream_V_V_17_empty_n,
        weights_stream_0_0_0_017_read => grp_CreateBitMask_fu_171_weights_stream_0_0_0_017_read,
        weights_stream_0_0_0_018_dout => weights_stream_V_V_18_dout,
        weights_stream_0_0_0_018_empty_n => weights_stream_V_V_18_empty_n,
        weights_stream_0_0_0_018_read => grp_CreateBitMask_fu_171_weights_stream_0_0_0_018_read,
        weights_stream_0_0_0_019_dout => weights_stream_V_V_19_dout,
        weights_stream_0_0_0_019_empty_n => weights_stream_V_V_19_empty_n,
        weights_stream_0_0_0_019_read => grp_CreateBitMask_fu_171_weights_stream_0_0_0_019_read,
        weights_stream_0_0_0_020_dout => weights_stream_V_V_20_dout,
        weights_stream_0_0_0_020_empty_n => weights_stream_V_V_20_empty_n,
        weights_stream_0_0_0_020_read => grp_CreateBitMask_fu_171_weights_stream_0_0_0_020_read,
        weights_stream_0_0_0_021_dout => weights_stream_V_V_21_dout,
        weights_stream_0_0_0_021_empty_n => weights_stream_V_V_21_empty_n,
        weights_stream_0_0_0_021_read => grp_CreateBitMask_fu_171_weights_stream_0_0_0_021_read,
        weights_stream_0_0_0_022_dout => weights_stream_V_V_22_dout,
        weights_stream_0_0_0_022_empty_n => weights_stream_V_V_22_empty_n,
        weights_stream_0_0_0_022_read => grp_CreateBitMask_fu_171_weights_stream_0_0_0_022_read,
        weights_stream_0_0_0_023_dout => weights_stream_V_V_23_dout,
        weights_stream_0_0_0_023_empty_n => weights_stream_V_V_23_empty_n,
        weights_stream_0_0_0_023_read => grp_CreateBitMask_fu_171_weights_stream_0_0_0_023_read,
        weights_stream_0_0_0_024_dout => weights_stream_V_V_24_dout,
        weights_stream_0_0_0_024_empty_n => weights_stream_V_V_24_empty_n,
        weights_stream_0_0_0_024_read => grp_CreateBitMask_fu_171_weights_stream_0_0_0_024_read,
        weights_stream_0_0_0_025_dout => weights_stream_V_V_25_dout,
        weights_stream_0_0_0_025_empty_n => weights_stream_V_V_25_empty_n,
        weights_stream_0_0_0_025_read => grp_CreateBitMask_fu_171_weights_stream_0_0_0_025_read,
        weights_stream_0_0_0_026_dout => weights_stream_V_V_26_dout,
        weights_stream_0_0_0_026_empty_n => weights_stream_V_V_26_empty_n,
        weights_stream_0_0_0_026_read => grp_CreateBitMask_fu_171_weights_stream_0_0_0_026_read,
        weights_stream_0_0_0_027_dout => weights_stream_V_V_27_dout,
        weights_stream_0_0_0_027_empty_n => weights_stream_V_V_27_empty_n,
        weights_stream_0_0_0_027_read => grp_CreateBitMask_fu_171_weights_stream_0_0_0_027_read,
        weights_stream_0_0_0_028_dout => weights_stream_V_V_28_dout,
        weights_stream_0_0_0_028_empty_n => weights_stream_V_V_28_empty_n,
        weights_stream_0_0_0_028_read => grp_CreateBitMask_fu_171_weights_stream_0_0_0_028_read,
        weights_stream_0_0_0_029_dout => weights_stream_V_V_29_dout,
        weights_stream_0_0_0_029_empty_n => weights_stream_V_V_29_empty_n,
        weights_stream_0_0_0_029_read => grp_CreateBitMask_fu_171_weights_stream_0_0_0_029_read,
        weights_stream_0_0_0_030_dout => weights_stream_V_V_30_dout,
        weights_stream_0_0_0_030_empty_n => weights_stream_V_V_30_empty_n,
        weights_stream_0_0_0_030_read => grp_CreateBitMask_fu_171_weights_stream_0_0_0_030_read,
        weights_stream_0_0_0_031_dout => weights_stream_V_V_31_dout,
        weights_stream_0_0_0_031_empty_n => weights_stream_V_V_31_empty_n,
        weights_stream_0_0_0_031_read => grp_CreateBitMask_fu_171_weights_stream_0_0_0_031_read,
        processing_buffer_address0 => grp_CreateBitMask_fu_171_processing_buffer_address0,
        processing_buffer_ce0 => grp_CreateBitMask_fu_171_processing_buffer_ce0,
        processing_buffer_we0 => grp_CreateBitMask_fu_171_processing_buffer_we0,
        processing_buffer_d0 => grp_CreateBitMask_fu_171_processing_buffer_d0,
        bit_buffer_weights_address0 => grp_CreateBitMask_fu_171_bit_buffer_weights_address0,
        bit_buffer_weights_ce0 => grp_CreateBitMask_fu_171_bit_buffer_weights_ce0,
        bit_buffer_weights_we0 => grp_CreateBitMask_fu_171_bit_buffer_weights_we0,
        bit_buffer_weights_d0 => grp_CreateBitMask_fu_171_bit_buffer_weights_d0);

    grp_RunDataFlow_Pipeline_VITIS_LOOP_341_1_fu_243 : component LINEAR_RunDataFlow_Pipeline_VITIS_LOOP_341_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_RunDataFlow_Pipeline_VITIS_LOOP_341_1_fu_243_ap_start,
        ap_done => grp_RunDataFlow_Pipeline_VITIS_LOOP_341_1_fu_243_ap_done,
        ap_idle => grp_RunDataFlow_Pipeline_VITIS_LOOP_341_1_fu_243_ap_idle,
        ap_ready => grp_RunDataFlow_Pipeline_VITIS_LOOP_341_1_fu_243_ap_ready,
        iacts_stream_dout => iacts_stream_dout,
        iacts_stream_empty_n => iacts_stream_empty_n,
        iacts_stream_read => grp_RunDataFlow_Pipeline_VITIS_LOOP_341_1_fu_243_iacts_stream_read,
        IACT_TEMP_BUFFER_V_address0 => grp_RunDataFlow_Pipeline_VITIS_LOOP_341_1_fu_243_IACT_TEMP_BUFFER_V_address0,
        IACT_TEMP_BUFFER_V_ce0 => grp_RunDataFlow_Pipeline_VITIS_LOOP_341_1_fu_243_IACT_TEMP_BUFFER_V_ce0,
        IACT_TEMP_BUFFER_V_we0 => grp_RunDataFlow_Pipeline_VITIS_LOOP_341_1_fu_243_IACT_TEMP_BUFFER_V_we0,
        IACT_TEMP_BUFFER_V_d0 => grp_RunDataFlow_Pipeline_VITIS_LOOP_341_1_fu_243_IACT_TEMP_BUFFER_V_d0);

    grp_DPEComputation_fu_250 : component LINEAR_DPEComputation
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_DPEComputation_fu_250_ap_start,
        ap_done => grp_DPEComputation_fu_250_ap_done,
        ap_idle => grp_DPEComputation_fu_250_ap_idle,
        ap_ready => grp_DPEComputation_fu_250_ap_ready,
        IACT_TEMP_BUFFER_address0 => grp_DPEComputation_fu_250_IACT_TEMP_BUFFER_address0,
        IACT_TEMP_BUFFER_ce0 => grp_DPEComputation_fu_250_IACT_TEMP_BUFFER_ce0,
        IACT_TEMP_BUFFER_q0 => IACT_TEMP_BUFFER_V_q0,
        block_idx_x => i_2_reg_400,
        block_idx_y => trunc_ln357_reg_418,
        processing_buffer_address0 => grp_DPEComputation_fu_250_processing_buffer_address0,
        processing_buffer_ce0 => grp_DPEComputation_fu_250_processing_buffer_ce0,
        processing_buffer_q0 => grp_DPEComputation_fu_250_processing_buffer_q0,
        bit_buffer_weights_address0 => grp_DPEComputation_fu_250_bit_buffer_weights_address0,
        bit_buffer_weights_ce0 => grp_DPEComputation_fu_250_bit_buffer_weights_ce0,
        bit_buffer_weights_q0 => grp_DPEComputation_fu_250_bit_buffer_weights_q0,
        buffer_out_address0 => grp_DPEComputation_fu_250_buffer_out_address0,
        buffer_out_ce0 => grp_DPEComputation_fu_250_buffer_out_ce0,
        buffer_out_we0 => grp_DPEComputation_fu_250_buffer_out_we0,
        buffer_out_d0 => grp_DPEComputation_fu_250_buffer_out_d0,
        buffer_out_q0 => output_buf_V_q0);

    mul_28s_28s_32_1_1_U589 : component LINEAR_mul_28s_28s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 28,
        din1_WIDTH => 28,
        dout_WIDTH => 32)
    port map (
        din0 => p_read1,
        din1 => p_read,
        dout => mul2_i_fu_279_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((icmp_ln352_fu_306_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_CreateBitMask_fu_171_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_CreateBitMask_fu_171_ap_start_reg <= ap_const_logic_0;
            else
                if ((((icmp_ln359_fu_350_p2 = ap_const_lv1_0) and (icmp_ln357_fu_330_p2 = ap_const_lv1_1) and (trunc_ln358_fu_346_p1 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5)) or ((icmp_ln359_fu_350_p2 = ap_const_lv1_0) and (icmp_ln357_fu_330_p2 = ap_const_lv1_1) and (trunc_ln358_fu_346_p1 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5)) or (not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                    grp_CreateBitMask_fu_171_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_CreateBitMask_fu_171_ap_ready = ap_const_logic_1)) then 
                    grp_CreateBitMask_fu_171_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_DPEComputation_fu_250_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_DPEComputation_fu_250_ap_start_reg <= ap_const_logic_0;
            else
                if ((((icmp_ln359_fu_350_p2 = ap_const_lv1_1) and (icmp_ln357_fu_330_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5)) or ((icmp_ln359_fu_350_p2 = ap_const_lv1_0) and (icmp_ln357_fu_330_p2 = ap_const_lv1_1) and (trunc_ln358_fu_346_p1 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5)) or ((icmp_ln359_fu_350_p2 = ap_const_lv1_0) and (icmp_ln357_fu_330_p2 = ap_const_lv1_1) and (trunc_ln358_fu_346_p1 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5)))) then 
                    grp_DPEComputation_fu_250_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_DPEComputation_fu_250_ap_ready = ap_const_logic_1)) then 
                    grp_DPEComputation_fu_250_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_RunDataFlow_Pipeline_VITIS_LOOP_341_1_fu_243_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_RunDataFlow_Pipeline_VITIS_LOOP_341_1_fu_243_ap_start_reg <= ap_const_logic_0;
            else
                if (((icmp_ln352_fu_306_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                    grp_RunDataFlow_Pipeline_VITIS_LOOP_341_1_fu_243_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_RunDataFlow_Pipeline_VITIS_LOOP_341_1_fu_243_ap_ready = ap_const_logic_1)) then 
                    grp_RunDataFlow_Pipeline_VITIS_LOOP_341_1_fu_243_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    i_fu_124_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                i_fu_124 <= ap_const_lv27_0;
            elsif (((icmp_ln357_fu_330_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                i_fu_124 <= i_3_reg_413;
            end if; 
        end if;
    end process;

    j_reg_160_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state6_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
                j_reg_160 <= j_1_reg_426;
            elsif (((grp_RunDataFlow_Pipeline_VITIS_LOOP_341_1_fu_243_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                j_reg_160 <= ap_const_lv27_0;
            end if; 
        end if;
    end process;

    phi_mul_fu_120_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                phi_mul_fu_120 <= ap_const_lv32_0;
            elsif (((icmp_ln357_fu_330_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                phi_mul_fu_120 <= add_ln352_reg_405;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                add_ln352_reg_405 <= add_ln352_fu_297_p2;
                i_2_reg_400 <= i_fu_124;
                i_3_reg_413 <= i_3_fu_311_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                block_num_y_cast_i_reg_387 <= block_num_y_cast_i_fu_271_p1;
                sub_i_reg_392 <= sub_i_fu_285_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln357_fu_330_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                icmp_ln359_reg_435 <= icmp_ln359_fu_350_p2;
                trunc_ln358_reg_431 <= trunc_ln358_fu_346_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                j_1_reg_426 <= j_1_fu_335_p2;
                trunc_ln357_reg_418 <= trunc_ln357_fu_325_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state5, icmp_ln357_fu_330_p2, grp_CreateBitMask_fu_171_ap_done, grp_RunDataFlow_Pipeline_VITIS_LOOP_341_1_fu_243_ap_done, ap_CS_fsm_state4, ap_CS_fsm_state6, ap_block_state6_on_subcall_done, icmp_ln352_fu_306_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_CreateBitMask_fu_171_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if (((icmp_ln352_fu_306_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                if (((grp_RunDataFlow_Pipeline_VITIS_LOOP_341_1_fu_243_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                if (((icmp_ln357_fu_330_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state6 => 
                if (((ap_const_boolean_0 = ap_block_state6_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;

    IACT_TEMP_BUFFER_V_address0_assign_proc : process(icmp_ln359_reg_435, grp_RunDataFlow_Pipeline_VITIS_LOOP_341_1_fu_243_IACT_TEMP_BUFFER_V_address0, grp_DPEComputation_fu_250_IACT_TEMP_BUFFER_address0, ap_CS_fsm_state4, ap_CS_fsm_state6, ap_predicate_op97_call_state6, ap_predicate_op100_call_state6)
    begin
        if ((((icmp_ln359_reg_435 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((ap_predicate_op100_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((ap_predicate_op97_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            IACT_TEMP_BUFFER_V_address0 <= grp_DPEComputation_fu_250_IACT_TEMP_BUFFER_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            IACT_TEMP_BUFFER_V_address0 <= grp_RunDataFlow_Pipeline_VITIS_LOOP_341_1_fu_243_IACT_TEMP_BUFFER_V_address0;
        else 
            IACT_TEMP_BUFFER_V_address0 <= "XXXXX";
        end if; 
    end process;


    IACT_TEMP_BUFFER_V_ce0_assign_proc : process(icmp_ln359_reg_435, grp_RunDataFlow_Pipeline_VITIS_LOOP_341_1_fu_243_IACT_TEMP_BUFFER_V_ce0, grp_DPEComputation_fu_250_IACT_TEMP_BUFFER_ce0, ap_CS_fsm_state4, ap_CS_fsm_state6, ap_predicate_op97_call_state6, ap_predicate_op100_call_state6)
    begin
        if ((((icmp_ln359_reg_435 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((ap_predicate_op100_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((ap_predicate_op97_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            IACT_TEMP_BUFFER_V_ce0 <= grp_DPEComputation_fu_250_IACT_TEMP_BUFFER_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            IACT_TEMP_BUFFER_V_ce0 <= grp_RunDataFlow_Pipeline_VITIS_LOOP_341_1_fu_243_IACT_TEMP_BUFFER_V_ce0;
        else 
            IACT_TEMP_BUFFER_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    IACT_TEMP_BUFFER_V_we0_assign_proc : process(grp_RunDataFlow_Pipeline_VITIS_LOOP_341_1_fu_243_IACT_TEMP_BUFFER_V_we0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            IACT_TEMP_BUFFER_V_we0 <= grp_RunDataFlow_Pipeline_VITIS_LOOP_341_1_fu_243_IACT_TEMP_BUFFER_V_we0;
        else 
            IACT_TEMP_BUFFER_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    add_ln352_fu_297_p2 <= std_logic_vector(unsigned(phi_mul_fu_120) + unsigned(block_num_y_cast_i_reg_387));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start, ap_done_reg)
    begin
        if (((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_CreateBitMask_fu_171_ap_done)
    begin
        if ((grp_CreateBitMask_fu_171_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_RunDataFlow_Pipeline_VITIS_LOOP_341_1_fu_243_ap_done)
    begin
        if ((grp_RunDataFlow_Pipeline_VITIS_LOOP_341_1_fu_243_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_ST_fsm_state6_blk_assign_proc : process(ap_block_state6_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state6_on_subcall_done)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0));
    end process;


    ap_block_state1_ignore_call48_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1_ignore_call48 <= ((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0));
    end process;


    ap_block_state6_on_subcall_done_assign_proc : process(icmp_ln359_reg_435, grp_CreateBitMask_fu_171_ap_done, grp_DPEComputation_fu_250_ap_done, ap_predicate_op96_call_state6, ap_predicate_op97_call_state6, ap_predicate_op99_call_state6, ap_predicate_op100_call_state6)
    begin
                ap_block_state6_on_subcall_done <= (((ap_predicate_op100_call_state6 = ap_const_boolean_1) and (grp_DPEComputation_fu_250_ap_done = ap_const_logic_0)) or ((ap_predicate_op99_call_state6 = ap_const_boolean_1) and (grp_CreateBitMask_fu_171_ap_done = ap_const_logic_0)) or ((ap_predicate_op97_call_state6 = ap_const_boolean_1) and (grp_DPEComputation_fu_250_ap_done = ap_const_logic_0)) or ((grp_DPEComputation_fu_250_ap_done = ap_const_logic_0) and (icmp_ln359_reg_435 = ap_const_lv1_1)) or ((ap_predicate_op96_call_state6 = ap_const_boolean_1) and (grp_CreateBitMask_fu_171_ap_done = ap_const_logic_0)));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state3, icmp_ln352_fu_306_p2)
    begin
        if (((icmp_ln352_fu_306_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_predicate_op100_call_state6_assign_proc : process(trunc_ln358_reg_431, icmp_ln359_reg_435)
    begin
                ap_predicate_op100_call_state6 <= ((icmp_ln359_reg_435 = ap_const_lv1_0) and (trunc_ln358_reg_431 = ap_const_lv1_1));
    end process;


    ap_predicate_op96_call_state6_assign_proc : process(trunc_ln358_reg_431, icmp_ln359_reg_435)
    begin
                ap_predicate_op96_call_state6 <= ((icmp_ln359_reg_435 = ap_const_lv1_0) and (trunc_ln358_reg_431 = ap_const_lv1_0));
    end process;


    ap_predicate_op97_call_state6_assign_proc : process(trunc_ln358_reg_431, icmp_ln359_reg_435)
    begin
                ap_predicate_op97_call_state6 <= ((icmp_ln359_reg_435 = ap_const_lv1_0) and (trunc_ln358_reg_431 = ap_const_lv1_0));
    end process;


    ap_predicate_op99_call_state6_assign_proc : process(trunc_ln358_reg_431, icmp_ln359_reg_435)
    begin
                ap_predicate_op99_call_state6 <= ((icmp_ln359_reg_435 = ap_const_lv1_0) and (trunc_ln358_reg_431 = ap_const_lv1_1));
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state3, icmp_ln352_fu_306_p2)
    begin
        if (((icmp_ln352_fu_306_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    batch_fu_341_p2 <= std_logic_vector(unsigned(phi_mul_fu_120) + unsigned(zext_ln357_fu_317_p1));
    block_num_y_cast_i_fu_271_p0 <= p_read1;
        block_num_y_cast_i_fu_271_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(block_num_y_cast_i_fu_271_p0),32));


    first_bit_buffer_weights_V_address0_assign_proc : process(ap_CS_fsm_state2, grp_CreateBitMask_fu_171_bit_buffer_weights_address0, grp_DPEComputation_fu_250_bit_buffer_weights_address0, ap_CS_fsm_state6, ap_predicate_op97_call_state6, ap_predicate_op99_call_state6)
    begin
        if (((ap_predicate_op97_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            first_bit_buffer_weights_V_address0 <= grp_DPEComputation_fu_250_bit_buffer_weights_address0;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_predicate_op99_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            first_bit_buffer_weights_V_address0 <= grp_CreateBitMask_fu_171_bit_buffer_weights_address0;
        else 
            first_bit_buffer_weights_V_address0 <= "XXXXX";
        end if; 
    end process;


    first_bit_buffer_weights_V_ce0_assign_proc : process(ap_CS_fsm_state2, grp_CreateBitMask_fu_171_bit_buffer_weights_ce0, grp_DPEComputation_fu_250_bit_buffer_weights_ce0, ap_CS_fsm_state6, ap_predicate_op97_call_state6, ap_predicate_op99_call_state6)
    begin
        if (((ap_predicate_op97_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            first_bit_buffer_weights_V_ce0 <= grp_DPEComputation_fu_250_bit_buffer_weights_ce0;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_predicate_op99_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            first_bit_buffer_weights_V_ce0 <= grp_CreateBitMask_fu_171_bit_buffer_weights_ce0;
        else 
            first_bit_buffer_weights_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    first_bit_buffer_weights_V_we0_assign_proc : process(ap_CS_fsm_state2, grp_CreateBitMask_fu_171_bit_buffer_weights_we0, ap_CS_fsm_state6, ap_predicate_op99_call_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_predicate_op99_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            first_bit_buffer_weights_V_we0 <= grp_CreateBitMask_fu_171_bit_buffer_weights_we0;
        else 
            first_bit_buffer_weights_V_we0 <= ap_const_logic_0;
        end if; 
    end process;


    first_processing_buffer_V_address0_assign_proc : process(ap_CS_fsm_state2, grp_CreateBitMask_fu_171_processing_buffer_address0, grp_DPEComputation_fu_250_processing_buffer_address0, ap_CS_fsm_state6, ap_predicate_op97_call_state6, ap_predicate_op99_call_state6)
    begin
        if (((ap_predicate_op97_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            first_processing_buffer_V_address0 <= grp_DPEComputation_fu_250_processing_buffer_address0;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_predicate_op99_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            first_processing_buffer_V_address0 <= grp_CreateBitMask_fu_171_processing_buffer_address0;
        else 
            first_processing_buffer_V_address0 <= "XXXXX";
        end if; 
    end process;


    first_processing_buffer_V_ce0_assign_proc : process(ap_CS_fsm_state2, grp_CreateBitMask_fu_171_processing_buffer_ce0, grp_DPEComputation_fu_250_processing_buffer_ce0, ap_CS_fsm_state6, ap_predicate_op97_call_state6, ap_predicate_op99_call_state6)
    begin
        if (((ap_predicate_op97_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            first_processing_buffer_V_ce0 <= grp_DPEComputation_fu_250_processing_buffer_ce0;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_predicate_op99_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            first_processing_buffer_V_ce0 <= grp_CreateBitMask_fu_171_processing_buffer_ce0;
        else 
            first_processing_buffer_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    first_processing_buffer_V_we0_assign_proc : process(ap_CS_fsm_state2, grp_CreateBitMask_fu_171_processing_buffer_we0, ap_CS_fsm_state6, ap_predicate_op99_call_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_predicate_op99_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            first_processing_buffer_V_we0 <= grp_CreateBitMask_fu_171_processing_buffer_we0;
        else 
            first_processing_buffer_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    grp_CreateBitMask_fu_171_ap_start <= grp_CreateBitMask_fu_171_ap_start_reg;
    grp_DPEComputation_fu_250_ap_start <= grp_DPEComputation_fu_250_ap_start_reg;

    grp_DPEComputation_fu_250_bit_buffer_weights_q0_assign_proc : process(icmp_ln359_reg_435, first_bit_buffer_weights_V_q0, second_bit_buffer_weights_V_q0, ap_CS_fsm_state6, ap_predicate_op97_call_state6, ap_predicate_op100_call_state6)
    begin
        if ((((icmp_ln359_reg_435 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((ap_predicate_op100_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            grp_DPEComputation_fu_250_bit_buffer_weights_q0 <= second_bit_buffer_weights_V_q0;
        elsif (((ap_predicate_op97_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            grp_DPEComputation_fu_250_bit_buffer_weights_q0 <= first_bit_buffer_weights_V_q0;
        else 
            grp_DPEComputation_fu_250_bit_buffer_weights_q0 <= "XXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_DPEComputation_fu_250_processing_buffer_q0_assign_proc : process(icmp_ln359_reg_435, first_processing_buffer_V_q0, second_processing_buffer_V_q0, ap_CS_fsm_state6, ap_predicate_op97_call_state6, ap_predicate_op100_call_state6)
    begin
        if ((((icmp_ln359_reg_435 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((ap_predicate_op100_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            grp_DPEComputation_fu_250_processing_buffer_q0 <= second_processing_buffer_V_q0;
        elsif (((ap_predicate_op97_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            grp_DPEComputation_fu_250_processing_buffer_q0 <= first_processing_buffer_V_q0;
        else 
            grp_DPEComputation_fu_250_processing_buffer_q0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    grp_RunDataFlow_Pipeline_VITIS_LOOP_341_1_fu_243_ap_start <= grp_RunDataFlow_Pipeline_VITIS_LOOP_341_1_fu_243_ap_start_reg;
    i_3_fu_311_p2 <= std_logic_vector(unsigned(i_fu_124) + unsigned(ap_const_lv27_1));

    iacts_stream_read_assign_proc : process(grp_RunDataFlow_Pipeline_VITIS_LOOP_341_1_fu_243_iacts_stream_read, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            iacts_stream_read <= grp_RunDataFlow_Pipeline_VITIS_LOOP_341_1_fu_243_iacts_stream_read;
        else 
            iacts_stream_read <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln352_fu_306_p1 <= p_read;
    icmp_ln352_fu_306_p2 <= "1" when (signed(zext_ln352_fu_302_p1) < signed(icmp_ln352_fu_306_p1)) else "0";
    icmp_ln357_fu_330_p1 <= p_read1;
    icmp_ln357_fu_330_p2 <= "1" when (signed(zext_ln357_1_fu_321_p1) < signed(icmp_ln357_fu_330_p1)) else "0";
    icmp_ln359_fu_350_p2 <= "1" when (batch_fu_341_p2 = sub_i_reg_392) else "0";
    j_1_fu_335_p2 <= std_logic_vector(unsigned(j_reg_160) + unsigned(ap_const_lv27_1));
    output_buf_V_address0 <= grp_DPEComputation_fu_250_buffer_out_address0;

    output_buf_V_ce0_assign_proc : process(icmp_ln359_reg_435, grp_DPEComputation_fu_250_buffer_out_ce0, ap_CS_fsm_state6, ap_predicate_op97_call_state6, ap_predicate_op100_call_state6)
    begin
        if ((((icmp_ln359_reg_435 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((ap_predicate_op100_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((ap_predicate_op97_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            output_buf_V_ce0 <= grp_DPEComputation_fu_250_buffer_out_ce0;
        else 
            output_buf_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    output_buf_V_d0 <= grp_DPEComputation_fu_250_buffer_out_d0;

    output_buf_V_we0_assign_proc : process(icmp_ln359_reg_435, grp_DPEComputation_fu_250_buffer_out_we0, ap_CS_fsm_state6, ap_predicate_op97_call_state6, ap_predicate_op100_call_state6)
    begin
        if ((((icmp_ln359_reg_435 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((ap_predicate_op100_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((ap_predicate_op97_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            output_buf_V_we0 <= grp_DPEComputation_fu_250_buffer_out_we0;
        else 
            output_buf_V_we0 <= ap_const_logic_0;
        end if; 
    end process;


    second_bit_buffer_weights_V_address0_assign_proc : process(icmp_ln359_reg_435, grp_CreateBitMask_fu_171_bit_buffer_weights_address0, grp_DPEComputation_fu_250_bit_buffer_weights_address0, ap_CS_fsm_state6, ap_predicate_op96_call_state6, ap_predicate_op100_call_state6)
    begin
        if ((((icmp_ln359_reg_435 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((ap_predicate_op100_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            second_bit_buffer_weights_V_address0 <= grp_DPEComputation_fu_250_bit_buffer_weights_address0;
        elsif (((ap_predicate_op96_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            second_bit_buffer_weights_V_address0 <= grp_CreateBitMask_fu_171_bit_buffer_weights_address0;
        else 
            second_bit_buffer_weights_V_address0 <= "XXXXX";
        end if; 
    end process;


    second_bit_buffer_weights_V_ce0_assign_proc : process(icmp_ln359_reg_435, grp_CreateBitMask_fu_171_bit_buffer_weights_ce0, grp_DPEComputation_fu_250_bit_buffer_weights_ce0, ap_CS_fsm_state6, ap_predicate_op96_call_state6, ap_predicate_op100_call_state6)
    begin
        if ((((icmp_ln359_reg_435 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((ap_predicate_op100_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            second_bit_buffer_weights_V_ce0 <= grp_DPEComputation_fu_250_bit_buffer_weights_ce0;
        elsif (((ap_predicate_op96_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            second_bit_buffer_weights_V_ce0 <= grp_CreateBitMask_fu_171_bit_buffer_weights_ce0;
        else 
            second_bit_buffer_weights_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    second_bit_buffer_weights_V_we0_assign_proc : process(grp_CreateBitMask_fu_171_bit_buffer_weights_we0, ap_CS_fsm_state6, ap_predicate_op96_call_state6)
    begin
        if (((ap_predicate_op96_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            second_bit_buffer_weights_V_we0 <= grp_CreateBitMask_fu_171_bit_buffer_weights_we0;
        else 
            second_bit_buffer_weights_V_we0 <= ap_const_logic_0;
        end if; 
    end process;


    second_processing_buffer_V_address0_assign_proc : process(icmp_ln359_reg_435, grp_CreateBitMask_fu_171_processing_buffer_address0, grp_DPEComputation_fu_250_processing_buffer_address0, ap_CS_fsm_state6, ap_predicate_op96_call_state6, ap_predicate_op100_call_state6)
    begin
        if ((((icmp_ln359_reg_435 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((ap_predicate_op100_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            second_processing_buffer_V_address0 <= grp_DPEComputation_fu_250_processing_buffer_address0;
        elsif (((ap_predicate_op96_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            second_processing_buffer_V_address0 <= grp_CreateBitMask_fu_171_processing_buffer_address0;
        else 
            second_processing_buffer_V_address0 <= "XXXXX";
        end if; 
    end process;


    second_processing_buffer_V_ce0_assign_proc : process(icmp_ln359_reg_435, grp_CreateBitMask_fu_171_processing_buffer_ce0, grp_DPEComputation_fu_250_processing_buffer_ce0, ap_CS_fsm_state6, ap_predicate_op96_call_state6, ap_predicate_op100_call_state6)
    begin
        if ((((icmp_ln359_reg_435 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((ap_predicate_op100_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            second_processing_buffer_V_ce0 <= grp_DPEComputation_fu_250_processing_buffer_ce0;
        elsif (((ap_predicate_op96_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            second_processing_buffer_V_ce0 <= grp_CreateBitMask_fu_171_processing_buffer_ce0;
        else 
            second_processing_buffer_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    second_processing_buffer_V_we0_assign_proc : process(grp_CreateBitMask_fu_171_processing_buffer_we0, ap_CS_fsm_state6, ap_predicate_op96_call_state6)
    begin
        if (((ap_predicate_op96_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            second_processing_buffer_V_we0 <= grp_CreateBitMask_fu_171_processing_buffer_we0;
        else 
            second_processing_buffer_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    sub_i_fu_285_p2 <= std_logic_vector(unsigned(mul2_i_fu_279_p2) + unsigned(ap_const_lv32_FFFFFFFF));
    trunc_ln357_fu_325_p1 <= j_reg_160(6 - 1 downto 0);
    trunc_ln358_fu_346_p1 <= batch_fu_341_p2(1 - 1 downto 0);

    weights_stream_V_V_0_read_assign_proc : process(ap_CS_fsm_state2, grp_CreateBitMask_fu_171_weights_stream_0_0_0_0_read, ap_CS_fsm_state6, ap_predicate_op96_call_state6, ap_predicate_op99_call_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_predicate_op99_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((ap_predicate_op96_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            weights_stream_V_V_0_read <= grp_CreateBitMask_fu_171_weights_stream_0_0_0_0_read;
        else 
            weights_stream_V_V_0_read <= ap_const_logic_0;
        end if; 
    end process;


    weights_stream_V_V_10_read_assign_proc : process(ap_CS_fsm_state2, grp_CreateBitMask_fu_171_weights_stream_0_0_0_010_read, ap_CS_fsm_state6, ap_predicate_op96_call_state6, ap_predicate_op99_call_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_predicate_op99_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((ap_predicate_op96_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            weights_stream_V_V_10_read <= grp_CreateBitMask_fu_171_weights_stream_0_0_0_010_read;
        else 
            weights_stream_V_V_10_read <= ap_const_logic_0;
        end if; 
    end process;


    weights_stream_V_V_11_read_assign_proc : process(ap_CS_fsm_state2, grp_CreateBitMask_fu_171_weights_stream_0_0_0_011_read, ap_CS_fsm_state6, ap_predicate_op96_call_state6, ap_predicate_op99_call_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_predicate_op99_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((ap_predicate_op96_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            weights_stream_V_V_11_read <= grp_CreateBitMask_fu_171_weights_stream_0_0_0_011_read;
        else 
            weights_stream_V_V_11_read <= ap_const_logic_0;
        end if; 
    end process;


    weights_stream_V_V_12_read_assign_proc : process(ap_CS_fsm_state2, grp_CreateBitMask_fu_171_weights_stream_0_0_0_012_read, ap_CS_fsm_state6, ap_predicate_op96_call_state6, ap_predicate_op99_call_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_predicate_op99_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((ap_predicate_op96_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            weights_stream_V_V_12_read <= grp_CreateBitMask_fu_171_weights_stream_0_0_0_012_read;
        else 
            weights_stream_V_V_12_read <= ap_const_logic_0;
        end if; 
    end process;


    weights_stream_V_V_13_read_assign_proc : process(ap_CS_fsm_state2, grp_CreateBitMask_fu_171_weights_stream_0_0_0_013_read, ap_CS_fsm_state6, ap_predicate_op96_call_state6, ap_predicate_op99_call_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_predicate_op99_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((ap_predicate_op96_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            weights_stream_V_V_13_read <= grp_CreateBitMask_fu_171_weights_stream_0_0_0_013_read;
        else 
            weights_stream_V_V_13_read <= ap_const_logic_0;
        end if; 
    end process;


    weights_stream_V_V_14_read_assign_proc : process(ap_CS_fsm_state2, grp_CreateBitMask_fu_171_weights_stream_0_0_0_014_read, ap_CS_fsm_state6, ap_predicate_op96_call_state6, ap_predicate_op99_call_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_predicate_op99_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((ap_predicate_op96_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            weights_stream_V_V_14_read <= grp_CreateBitMask_fu_171_weights_stream_0_0_0_014_read;
        else 
            weights_stream_V_V_14_read <= ap_const_logic_0;
        end if; 
    end process;


    weights_stream_V_V_15_read_assign_proc : process(ap_CS_fsm_state2, grp_CreateBitMask_fu_171_weights_stream_0_0_0_015_read, ap_CS_fsm_state6, ap_predicate_op96_call_state6, ap_predicate_op99_call_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_predicate_op99_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((ap_predicate_op96_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            weights_stream_V_V_15_read <= grp_CreateBitMask_fu_171_weights_stream_0_0_0_015_read;
        else 
            weights_stream_V_V_15_read <= ap_const_logic_0;
        end if; 
    end process;


    weights_stream_V_V_16_read_assign_proc : process(ap_CS_fsm_state2, grp_CreateBitMask_fu_171_weights_stream_0_0_0_016_read, ap_CS_fsm_state6, ap_predicate_op96_call_state6, ap_predicate_op99_call_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_predicate_op99_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((ap_predicate_op96_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            weights_stream_V_V_16_read <= grp_CreateBitMask_fu_171_weights_stream_0_0_0_016_read;
        else 
            weights_stream_V_V_16_read <= ap_const_logic_0;
        end if; 
    end process;


    weights_stream_V_V_17_read_assign_proc : process(ap_CS_fsm_state2, grp_CreateBitMask_fu_171_weights_stream_0_0_0_017_read, ap_CS_fsm_state6, ap_predicate_op96_call_state6, ap_predicate_op99_call_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_predicate_op99_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((ap_predicate_op96_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            weights_stream_V_V_17_read <= grp_CreateBitMask_fu_171_weights_stream_0_0_0_017_read;
        else 
            weights_stream_V_V_17_read <= ap_const_logic_0;
        end if; 
    end process;


    weights_stream_V_V_18_read_assign_proc : process(ap_CS_fsm_state2, grp_CreateBitMask_fu_171_weights_stream_0_0_0_018_read, ap_CS_fsm_state6, ap_predicate_op96_call_state6, ap_predicate_op99_call_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_predicate_op99_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((ap_predicate_op96_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            weights_stream_V_V_18_read <= grp_CreateBitMask_fu_171_weights_stream_0_0_0_018_read;
        else 
            weights_stream_V_V_18_read <= ap_const_logic_0;
        end if; 
    end process;


    weights_stream_V_V_19_read_assign_proc : process(ap_CS_fsm_state2, grp_CreateBitMask_fu_171_weights_stream_0_0_0_019_read, ap_CS_fsm_state6, ap_predicate_op96_call_state6, ap_predicate_op99_call_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_predicate_op99_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((ap_predicate_op96_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            weights_stream_V_V_19_read <= grp_CreateBitMask_fu_171_weights_stream_0_0_0_019_read;
        else 
            weights_stream_V_V_19_read <= ap_const_logic_0;
        end if; 
    end process;


    weights_stream_V_V_1_read_assign_proc : process(ap_CS_fsm_state2, grp_CreateBitMask_fu_171_weights_stream_0_0_0_01_read, ap_CS_fsm_state6, ap_predicate_op96_call_state6, ap_predicate_op99_call_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_predicate_op99_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((ap_predicate_op96_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            weights_stream_V_V_1_read <= grp_CreateBitMask_fu_171_weights_stream_0_0_0_01_read;
        else 
            weights_stream_V_V_1_read <= ap_const_logic_0;
        end if; 
    end process;


    weights_stream_V_V_20_read_assign_proc : process(ap_CS_fsm_state2, grp_CreateBitMask_fu_171_weights_stream_0_0_0_020_read, ap_CS_fsm_state6, ap_predicate_op96_call_state6, ap_predicate_op99_call_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_predicate_op99_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((ap_predicate_op96_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            weights_stream_V_V_20_read <= grp_CreateBitMask_fu_171_weights_stream_0_0_0_020_read;
        else 
            weights_stream_V_V_20_read <= ap_const_logic_0;
        end if; 
    end process;


    weights_stream_V_V_21_read_assign_proc : process(ap_CS_fsm_state2, grp_CreateBitMask_fu_171_weights_stream_0_0_0_021_read, ap_CS_fsm_state6, ap_predicate_op96_call_state6, ap_predicate_op99_call_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_predicate_op99_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((ap_predicate_op96_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            weights_stream_V_V_21_read <= grp_CreateBitMask_fu_171_weights_stream_0_0_0_021_read;
        else 
            weights_stream_V_V_21_read <= ap_const_logic_0;
        end if; 
    end process;


    weights_stream_V_V_22_read_assign_proc : process(ap_CS_fsm_state2, grp_CreateBitMask_fu_171_weights_stream_0_0_0_022_read, ap_CS_fsm_state6, ap_predicate_op96_call_state6, ap_predicate_op99_call_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_predicate_op99_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((ap_predicate_op96_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            weights_stream_V_V_22_read <= grp_CreateBitMask_fu_171_weights_stream_0_0_0_022_read;
        else 
            weights_stream_V_V_22_read <= ap_const_logic_0;
        end if; 
    end process;


    weights_stream_V_V_23_read_assign_proc : process(ap_CS_fsm_state2, grp_CreateBitMask_fu_171_weights_stream_0_0_0_023_read, ap_CS_fsm_state6, ap_predicate_op96_call_state6, ap_predicate_op99_call_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_predicate_op99_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((ap_predicate_op96_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            weights_stream_V_V_23_read <= grp_CreateBitMask_fu_171_weights_stream_0_0_0_023_read;
        else 
            weights_stream_V_V_23_read <= ap_const_logic_0;
        end if; 
    end process;


    weights_stream_V_V_24_read_assign_proc : process(ap_CS_fsm_state2, grp_CreateBitMask_fu_171_weights_stream_0_0_0_024_read, ap_CS_fsm_state6, ap_predicate_op96_call_state6, ap_predicate_op99_call_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_predicate_op99_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((ap_predicate_op96_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            weights_stream_V_V_24_read <= grp_CreateBitMask_fu_171_weights_stream_0_0_0_024_read;
        else 
            weights_stream_V_V_24_read <= ap_const_logic_0;
        end if; 
    end process;


    weights_stream_V_V_25_read_assign_proc : process(ap_CS_fsm_state2, grp_CreateBitMask_fu_171_weights_stream_0_0_0_025_read, ap_CS_fsm_state6, ap_predicate_op96_call_state6, ap_predicate_op99_call_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_predicate_op99_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((ap_predicate_op96_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            weights_stream_V_V_25_read <= grp_CreateBitMask_fu_171_weights_stream_0_0_0_025_read;
        else 
            weights_stream_V_V_25_read <= ap_const_logic_0;
        end if; 
    end process;


    weights_stream_V_V_26_read_assign_proc : process(ap_CS_fsm_state2, grp_CreateBitMask_fu_171_weights_stream_0_0_0_026_read, ap_CS_fsm_state6, ap_predicate_op96_call_state6, ap_predicate_op99_call_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_predicate_op99_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((ap_predicate_op96_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            weights_stream_V_V_26_read <= grp_CreateBitMask_fu_171_weights_stream_0_0_0_026_read;
        else 
            weights_stream_V_V_26_read <= ap_const_logic_0;
        end if; 
    end process;


    weights_stream_V_V_27_read_assign_proc : process(ap_CS_fsm_state2, grp_CreateBitMask_fu_171_weights_stream_0_0_0_027_read, ap_CS_fsm_state6, ap_predicate_op96_call_state6, ap_predicate_op99_call_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_predicate_op99_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((ap_predicate_op96_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            weights_stream_V_V_27_read <= grp_CreateBitMask_fu_171_weights_stream_0_0_0_027_read;
        else 
            weights_stream_V_V_27_read <= ap_const_logic_0;
        end if; 
    end process;


    weights_stream_V_V_28_read_assign_proc : process(ap_CS_fsm_state2, grp_CreateBitMask_fu_171_weights_stream_0_0_0_028_read, ap_CS_fsm_state6, ap_predicate_op96_call_state6, ap_predicate_op99_call_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_predicate_op99_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((ap_predicate_op96_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            weights_stream_V_V_28_read <= grp_CreateBitMask_fu_171_weights_stream_0_0_0_028_read;
        else 
            weights_stream_V_V_28_read <= ap_const_logic_0;
        end if; 
    end process;


    weights_stream_V_V_29_read_assign_proc : process(ap_CS_fsm_state2, grp_CreateBitMask_fu_171_weights_stream_0_0_0_029_read, ap_CS_fsm_state6, ap_predicate_op96_call_state6, ap_predicate_op99_call_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_predicate_op99_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((ap_predicate_op96_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            weights_stream_V_V_29_read <= grp_CreateBitMask_fu_171_weights_stream_0_0_0_029_read;
        else 
            weights_stream_V_V_29_read <= ap_const_logic_0;
        end if; 
    end process;


    weights_stream_V_V_2_read_assign_proc : process(ap_CS_fsm_state2, grp_CreateBitMask_fu_171_weights_stream_0_0_0_02_read, ap_CS_fsm_state6, ap_predicate_op96_call_state6, ap_predicate_op99_call_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_predicate_op99_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((ap_predicate_op96_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            weights_stream_V_V_2_read <= grp_CreateBitMask_fu_171_weights_stream_0_0_0_02_read;
        else 
            weights_stream_V_V_2_read <= ap_const_logic_0;
        end if; 
    end process;


    weights_stream_V_V_30_read_assign_proc : process(ap_CS_fsm_state2, grp_CreateBitMask_fu_171_weights_stream_0_0_0_030_read, ap_CS_fsm_state6, ap_predicate_op96_call_state6, ap_predicate_op99_call_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_predicate_op99_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((ap_predicate_op96_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            weights_stream_V_V_30_read <= grp_CreateBitMask_fu_171_weights_stream_0_0_0_030_read;
        else 
            weights_stream_V_V_30_read <= ap_const_logic_0;
        end if; 
    end process;


    weights_stream_V_V_31_read_assign_proc : process(ap_CS_fsm_state2, grp_CreateBitMask_fu_171_weights_stream_0_0_0_031_read, ap_CS_fsm_state6, ap_predicate_op96_call_state6, ap_predicate_op99_call_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_predicate_op99_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((ap_predicate_op96_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            weights_stream_V_V_31_read <= grp_CreateBitMask_fu_171_weights_stream_0_0_0_031_read;
        else 
            weights_stream_V_V_31_read <= ap_const_logic_0;
        end if; 
    end process;


    weights_stream_V_V_3_read_assign_proc : process(ap_CS_fsm_state2, grp_CreateBitMask_fu_171_weights_stream_0_0_0_03_read, ap_CS_fsm_state6, ap_predicate_op96_call_state6, ap_predicate_op99_call_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_predicate_op99_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((ap_predicate_op96_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            weights_stream_V_V_3_read <= grp_CreateBitMask_fu_171_weights_stream_0_0_0_03_read;
        else 
            weights_stream_V_V_3_read <= ap_const_logic_0;
        end if; 
    end process;


    weights_stream_V_V_4_read_assign_proc : process(ap_CS_fsm_state2, grp_CreateBitMask_fu_171_weights_stream_0_0_0_04_read, ap_CS_fsm_state6, ap_predicate_op96_call_state6, ap_predicate_op99_call_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_predicate_op99_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((ap_predicate_op96_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            weights_stream_V_V_4_read <= grp_CreateBitMask_fu_171_weights_stream_0_0_0_04_read;
        else 
            weights_stream_V_V_4_read <= ap_const_logic_0;
        end if; 
    end process;


    weights_stream_V_V_5_read_assign_proc : process(ap_CS_fsm_state2, grp_CreateBitMask_fu_171_weights_stream_0_0_0_05_read, ap_CS_fsm_state6, ap_predicate_op96_call_state6, ap_predicate_op99_call_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_predicate_op99_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((ap_predicate_op96_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            weights_stream_V_V_5_read <= grp_CreateBitMask_fu_171_weights_stream_0_0_0_05_read;
        else 
            weights_stream_V_V_5_read <= ap_const_logic_0;
        end if; 
    end process;


    weights_stream_V_V_6_read_assign_proc : process(ap_CS_fsm_state2, grp_CreateBitMask_fu_171_weights_stream_0_0_0_06_read, ap_CS_fsm_state6, ap_predicate_op96_call_state6, ap_predicate_op99_call_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_predicate_op99_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((ap_predicate_op96_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            weights_stream_V_V_6_read <= grp_CreateBitMask_fu_171_weights_stream_0_0_0_06_read;
        else 
            weights_stream_V_V_6_read <= ap_const_logic_0;
        end if; 
    end process;


    weights_stream_V_V_7_read_assign_proc : process(ap_CS_fsm_state2, grp_CreateBitMask_fu_171_weights_stream_0_0_0_07_read, ap_CS_fsm_state6, ap_predicate_op96_call_state6, ap_predicate_op99_call_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_predicate_op99_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((ap_predicate_op96_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            weights_stream_V_V_7_read <= grp_CreateBitMask_fu_171_weights_stream_0_0_0_07_read;
        else 
            weights_stream_V_V_7_read <= ap_const_logic_0;
        end if; 
    end process;


    weights_stream_V_V_8_read_assign_proc : process(ap_CS_fsm_state2, grp_CreateBitMask_fu_171_weights_stream_0_0_0_08_read, ap_CS_fsm_state6, ap_predicate_op96_call_state6, ap_predicate_op99_call_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_predicate_op99_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((ap_predicate_op96_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            weights_stream_V_V_8_read <= grp_CreateBitMask_fu_171_weights_stream_0_0_0_08_read;
        else 
            weights_stream_V_V_8_read <= ap_const_logic_0;
        end if; 
    end process;


    weights_stream_V_V_9_read_assign_proc : process(ap_CS_fsm_state2, grp_CreateBitMask_fu_171_weights_stream_0_0_0_09_read, ap_CS_fsm_state6, ap_predicate_op96_call_state6, ap_predicate_op99_call_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_predicate_op99_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((ap_predicate_op96_call_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            weights_stream_V_V_9_read <= grp_CreateBitMask_fu_171_weights_stream_0_0_0_09_read;
        else 
            weights_stream_V_V_9_read <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln352_fu_302_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_fu_124),28));
    zext_ln357_1_fu_321_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(j_reg_160),28));
    zext_ln357_fu_317_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(j_reg_160),32));
end behav;
