-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
-- Version: 2021.1
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity LINEAR_DPEComputation is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    IACT_TEMP_BUFFER_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    IACT_TEMP_BUFFER_ce0 : OUT STD_LOGIC;
    IACT_TEMP_BUFFER_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    block_idx_x : IN STD_LOGIC_VECTOR (26 downto 0);
    block_idx_y : IN STD_LOGIC_VECTOR (5 downto 0);
    processing_buffer_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    processing_buffer_ce0 : OUT STD_LOGIC;
    processing_buffer_q0 : IN STD_LOGIC_VECTOR (639 downto 0);
    bit_buffer_weights_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    bit_buffer_weights_ce0 : OUT STD_LOGIC;
    bit_buffer_weights_q0 : IN STD_LOGIC_VECTOR (19 downto 0);
    buffer_out_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    buffer_out_ce0 : OUT STD_LOGIC;
    buffer_out_we0 : OUT STD_LOGIC;
    buffer_out_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    buffer_out_q0 : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of LINEAR_DPEComputation is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv27_0 : STD_LOGIC_VECTOR (26 downto 0) := "000000000000000000000000000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_boolean_0 : BOOLEAN := false;

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal icmp_ln286_fu_92_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln286_reg_156 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln292_fu_118_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln292_reg_160 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln305_fu_143_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln305_reg_165 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal local_output_buf_V_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal local_output_buf_V_ce0 : STD_LOGIC;
    signal local_output_buf_V_we0 : STD_LOGIC;
    signal local_output_buf_V_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal local_output_buf_V_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal local_output_buf_V_ce1 : STD_LOGIC;
    signal local_output_buf_V_we1 : STD_LOGIC;
    signal local_output_buf_V_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_DPEComputation_Pipeline_VITIS_LOOP_291_2_fu_58_ap_start : STD_LOGIC;
    signal grp_DPEComputation_Pipeline_VITIS_LOOP_291_2_fu_58_ap_done : STD_LOGIC;
    signal grp_DPEComputation_Pipeline_VITIS_LOOP_291_2_fu_58_ap_idle : STD_LOGIC;
    signal grp_DPEComputation_Pipeline_VITIS_LOOP_291_2_fu_58_ap_ready : STD_LOGIC;
    signal grp_DPEComputation_Pipeline_VITIS_LOOP_291_2_fu_58_buffer_out_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DPEComputation_Pipeline_VITIS_LOOP_291_2_fu_58_buffer_out_ce0 : STD_LOGIC;
    signal grp_DPEComputation_Pipeline_VITIS_LOOP_291_2_fu_58_local_output_buf_V_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DPEComputation_Pipeline_VITIS_LOOP_291_2_fu_58_local_output_buf_V_ce0 : STD_LOGIC;
    signal grp_DPEComputation_Pipeline_VITIS_LOOP_291_2_fu_58_local_output_buf_V_we0 : STD_LOGIC;
    signal grp_DPEComputation_Pipeline_VITIS_LOOP_291_2_fu_58_local_output_buf_V_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_DPEComputation_Pipeline_VITIS_LOOP_287_1_fu_67_ap_start : STD_LOGIC;
    signal grp_DPEComputation_Pipeline_VITIS_LOOP_287_1_fu_67_ap_done : STD_LOGIC;
    signal grp_DPEComputation_Pipeline_VITIS_LOOP_287_1_fu_67_ap_idle : STD_LOGIC;
    signal grp_DPEComputation_Pipeline_VITIS_LOOP_287_1_fu_67_ap_ready : STD_LOGIC;
    signal grp_DPEComputation_Pipeline_VITIS_LOOP_287_1_fu_67_local_output_buf_V_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DPEComputation_Pipeline_VITIS_LOOP_287_1_fu_67_local_output_buf_V_ce0 : STD_LOGIC;
    signal grp_DPEComputation_Pipeline_VITIS_LOOP_287_1_fu_67_local_output_buf_V_we0 : STD_LOGIC;
    signal grp_DPEComputation_Pipeline_VITIS_LOOP_287_1_fu_67_local_output_buf_V_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_DPEComputation_Pipeline_VITIS_LOOP_296_3_fu_73_ap_start : STD_LOGIC;
    signal grp_DPEComputation_Pipeline_VITIS_LOOP_296_3_fu_73_ap_done : STD_LOGIC;
    signal grp_DPEComputation_Pipeline_VITIS_LOOP_296_3_fu_73_ap_idle : STD_LOGIC;
    signal grp_DPEComputation_Pipeline_VITIS_LOOP_296_3_fu_73_ap_ready : STD_LOGIC;
    signal grp_DPEComputation_Pipeline_VITIS_LOOP_296_3_fu_73_IACT_TEMP_BUFFER_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_DPEComputation_Pipeline_VITIS_LOOP_296_3_fu_73_IACT_TEMP_BUFFER_ce0 : STD_LOGIC;
    signal grp_DPEComputation_Pipeline_VITIS_LOOP_296_3_fu_73_processing_buffer_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_DPEComputation_Pipeline_VITIS_LOOP_296_3_fu_73_processing_buffer_ce0 : STD_LOGIC;
    signal grp_DPEComputation_Pipeline_VITIS_LOOP_296_3_fu_73_bit_buffer_weights_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_DPEComputation_Pipeline_VITIS_LOOP_296_3_fu_73_bit_buffer_weights_ce0 : STD_LOGIC;
    signal grp_DPEComputation_Pipeline_VITIS_LOOP_296_3_fu_73_local_output_buf_V_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DPEComputation_Pipeline_VITIS_LOOP_296_3_fu_73_local_output_buf_V_ce0 : STD_LOGIC;
    signal grp_DPEComputation_Pipeline_VITIS_LOOP_296_3_fu_73_local_output_buf_V_we0 : STD_LOGIC;
    signal grp_DPEComputation_Pipeline_VITIS_LOOP_296_3_fu_73_local_output_buf_V_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_DPEComputation_Pipeline_VITIS_LOOP_296_3_fu_73_local_output_buf_V_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DPEComputation_Pipeline_VITIS_LOOP_296_3_fu_73_local_output_buf_V_ce1 : STD_LOGIC;
    signal grp_DPEComputation_Pipeline_VITIS_LOOP_296_3_fu_73_local_output_buf_V_we1 : STD_LOGIC;
    signal grp_DPEComputation_Pipeline_VITIS_LOOP_296_3_fu_73_local_output_buf_V_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_DPEComputation_Pipeline_VITIS_LOOP_303_4_fu_84_ap_start : STD_LOGIC;
    signal grp_DPEComputation_Pipeline_VITIS_LOOP_303_4_fu_84_ap_done : STD_LOGIC;
    signal grp_DPEComputation_Pipeline_VITIS_LOOP_303_4_fu_84_ap_idle : STD_LOGIC;
    signal grp_DPEComputation_Pipeline_VITIS_LOOP_303_4_fu_84_ap_ready : STD_LOGIC;
    signal grp_DPEComputation_Pipeline_VITIS_LOOP_303_4_fu_84_buffer_out_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DPEComputation_Pipeline_VITIS_LOOP_303_4_fu_84_buffer_out_ce0 : STD_LOGIC;
    signal grp_DPEComputation_Pipeline_VITIS_LOOP_303_4_fu_84_buffer_out_we0 : STD_LOGIC;
    signal grp_DPEComputation_Pipeline_VITIS_LOOP_303_4_fu_84_buffer_out_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_DPEComputation_Pipeline_VITIS_LOOP_303_4_fu_84_local_output_buf_V_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DPEComputation_Pipeline_VITIS_LOOP_303_4_fu_84_local_output_buf_V_ce0 : STD_LOGIC;
    signal grp_DPEComputation_Pipeline_VITIS_LOOP_291_2_fu_58_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_DPEComputation_Pipeline_VITIS_LOOP_287_1_fu_67_ap_start_reg : STD_LOGIC := '0';
    signal grp_DPEComputation_Pipeline_VITIS_LOOP_296_3_fu_73_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal grp_DPEComputation_Pipeline_VITIS_LOOP_303_4_fu_84_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal tmp_s_fu_106_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_fu_98_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln292_fu_114_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_12_fu_132_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_11_fu_125_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln305_fu_139_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_block_state2_on_subcall_done : BOOLEAN;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component LINEAR_DPEComputation_Pipeline_VITIS_LOOP_291_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        add_ln292 : IN STD_LOGIC_VECTOR (9 downto 0);
        buffer_out_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        buffer_out_ce0 : OUT STD_LOGIC;
        buffer_out_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        local_output_buf_V_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        local_output_buf_V_ce0 : OUT STD_LOGIC;
        local_output_buf_V_we0 : OUT STD_LOGIC;
        local_output_buf_V_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component LINEAR_DPEComputation_Pipeline_VITIS_LOOP_287_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        local_output_buf_V_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        local_output_buf_V_ce0 : OUT STD_LOGIC;
        local_output_buf_V_we0 : OUT STD_LOGIC;
        local_output_buf_V_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component LINEAR_DPEComputation_Pipeline_VITIS_LOOP_296_3 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        IACT_TEMP_BUFFER_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        IACT_TEMP_BUFFER_ce0 : OUT STD_LOGIC;
        IACT_TEMP_BUFFER_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        processing_buffer_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        processing_buffer_ce0 : OUT STD_LOGIC;
        processing_buffer_q0 : IN STD_LOGIC_VECTOR (639 downto 0);
        bit_buffer_weights_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        bit_buffer_weights_ce0 : OUT STD_LOGIC;
        bit_buffer_weights_q0 : IN STD_LOGIC_VECTOR (19 downto 0);
        local_output_buf_V_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        local_output_buf_V_ce0 : OUT STD_LOGIC;
        local_output_buf_V_we0 : OUT STD_LOGIC;
        local_output_buf_V_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        local_output_buf_V_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        local_output_buf_V_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        local_output_buf_V_ce1 : OUT STD_LOGIC;
        local_output_buf_V_we1 : OUT STD_LOGIC;
        local_output_buf_V_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        local_output_buf_V_q1 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component LINEAR_DPEComputation_Pipeline_VITIS_LOOP_303_4 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        add_ln305 : IN STD_LOGIC_VECTOR (9 downto 0);
        buffer_out_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        buffer_out_ce0 : OUT STD_LOGIC;
        buffer_out_we0 : OUT STD_LOGIC;
        buffer_out_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        local_output_buf_V_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        local_output_buf_V_ce0 : OUT STD_LOGIC;
        local_output_buf_V_q0 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component LINEAR_DPEComputation_local_output_buf_V IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        address1 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (31 downto 0);
        q1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    local_output_buf_V_U : component LINEAR_DPEComputation_local_output_buf_V
    generic map (
        DataWidth => 32,
        AddressRange => 640,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => local_output_buf_V_address0,
        ce0 => local_output_buf_V_ce0,
        we0 => local_output_buf_V_we0,
        d0 => local_output_buf_V_d0,
        q0 => local_output_buf_V_q0,
        address1 => grp_DPEComputation_Pipeline_VITIS_LOOP_296_3_fu_73_local_output_buf_V_address1,
        ce1 => local_output_buf_V_ce1,
        we1 => local_output_buf_V_we1,
        d1 => grp_DPEComputation_Pipeline_VITIS_LOOP_296_3_fu_73_local_output_buf_V_d1,
        q1 => local_output_buf_V_q1);

    grp_DPEComputation_Pipeline_VITIS_LOOP_291_2_fu_58 : component LINEAR_DPEComputation_Pipeline_VITIS_LOOP_291_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_DPEComputation_Pipeline_VITIS_LOOP_291_2_fu_58_ap_start,
        ap_done => grp_DPEComputation_Pipeline_VITIS_LOOP_291_2_fu_58_ap_done,
        ap_idle => grp_DPEComputation_Pipeline_VITIS_LOOP_291_2_fu_58_ap_idle,
        ap_ready => grp_DPEComputation_Pipeline_VITIS_LOOP_291_2_fu_58_ap_ready,
        add_ln292 => add_ln292_reg_160,
        buffer_out_address0 => grp_DPEComputation_Pipeline_VITIS_LOOP_291_2_fu_58_buffer_out_address0,
        buffer_out_ce0 => grp_DPEComputation_Pipeline_VITIS_LOOP_291_2_fu_58_buffer_out_ce0,
        buffer_out_q0 => buffer_out_q0,
        local_output_buf_V_address0 => grp_DPEComputation_Pipeline_VITIS_LOOP_291_2_fu_58_local_output_buf_V_address0,
        local_output_buf_V_ce0 => grp_DPEComputation_Pipeline_VITIS_LOOP_291_2_fu_58_local_output_buf_V_ce0,
        local_output_buf_V_we0 => grp_DPEComputation_Pipeline_VITIS_LOOP_291_2_fu_58_local_output_buf_V_we0,
        local_output_buf_V_d0 => grp_DPEComputation_Pipeline_VITIS_LOOP_291_2_fu_58_local_output_buf_V_d0);

    grp_DPEComputation_Pipeline_VITIS_LOOP_287_1_fu_67 : component LINEAR_DPEComputation_Pipeline_VITIS_LOOP_287_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_DPEComputation_Pipeline_VITIS_LOOP_287_1_fu_67_ap_start,
        ap_done => grp_DPEComputation_Pipeline_VITIS_LOOP_287_1_fu_67_ap_done,
        ap_idle => grp_DPEComputation_Pipeline_VITIS_LOOP_287_1_fu_67_ap_idle,
        ap_ready => grp_DPEComputation_Pipeline_VITIS_LOOP_287_1_fu_67_ap_ready,
        local_output_buf_V_address0 => grp_DPEComputation_Pipeline_VITIS_LOOP_287_1_fu_67_local_output_buf_V_address0,
        local_output_buf_V_ce0 => grp_DPEComputation_Pipeline_VITIS_LOOP_287_1_fu_67_local_output_buf_V_ce0,
        local_output_buf_V_we0 => grp_DPEComputation_Pipeline_VITIS_LOOP_287_1_fu_67_local_output_buf_V_we0,
        local_output_buf_V_d0 => grp_DPEComputation_Pipeline_VITIS_LOOP_287_1_fu_67_local_output_buf_V_d0);

    grp_DPEComputation_Pipeline_VITIS_LOOP_296_3_fu_73 : component LINEAR_DPEComputation_Pipeline_VITIS_LOOP_296_3
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_DPEComputation_Pipeline_VITIS_LOOP_296_3_fu_73_ap_start,
        ap_done => grp_DPEComputation_Pipeline_VITIS_LOOP_296_3_fu_73_ap_done,
        ap_idle => grp_DPEComputation_Pipeline_VITIS_LOOP_296_3_fu_73_ap_idle,
        ap_ready => grp_DPEComputation_Pipeline_VITIS_LOOP_296_3_fu_73_ap_ready,
        IACT_TEMP_BUFFER_address0 => grp_DPEComputation_Pipeline_VITIS_LOOP_296_3_fu_73_IACT_TEMP_BUFFER_address0,
        IACT_TEMP_BUFFER_ce0 => grp_DPEComputation_Pipeline_VITIS_LOOP_296_3_fu_73_IACT_TEMP_BUFFER_ce0,
        IACT_TEMP_BUFFER_q0 => IACT_TEMP_BUFFER_q0,
        processing_buffer_address0 => grp_DPEComputation_Pipeline_VITIS_LOOP_296_3_fu_73_processing_buffer_address0,
        processing_buffer_ce0 => grp_DPEComputation_Pipeline_VITIS_LOOP_296_3_fu_73_processing_buffer_ce0,
        processing_buffer_q0 => processing_buffer_q0,
        bit_buffer_weights_address0 => grp_DPEComputation_Pipeline_VITIS_LOOP_296_3_fu_73_bit_buffer_weights_address0,
        bit_buffer_weights_ce0 => grp_DPEComputation_Pipeline_VITIS_LOOP_296_3_fu_73_bit_buffer_weights_ce0,
        bit_buffer_weights_q0 => bit_buffer_weights_q0,
        local_output_buf_V_address0 => grp_DPEComputation_Pipeline_VITIS_LOOP_296_3_fu_73_local_output_buf_V_address0,
        local_output_buf_V_ce0 => grp_DPEComputation_Pipeline_VITIS_LOOP_296_3_fu_73_local_output_buf_V_ce0,
        local_output_buf_V_we0 => grp_DPEComputation_Pipeline_VITIS_LOOP_296_3_fu_73_local_output_buf_V_we0,
        local_output_buf_V_d0 => grp_DPEComputation_Pipeline_VITIS_LOOP_296_3_fu_73_local_output_buf_V_d0,
        local_output_buf_V_q0 => local_output_buf_V_q0,
        local_output_buf_V_address1 => grp_DPEComputation_Pipeline_VITIS_LOOP_296_3_fu_73_local_output_buf_V_address1,
        local_output_buf_V_ce1 => grp_DPEComputation_Pipeline_VITIS_LOOP_296_3_fu_73_local_output_buf_V_ce1,
        local_output_buf_V_we1 => grp_DPEComputation_Pipeline_VITIS_LOOP_296_3_fu_73_local_output_buf_V_we1,
        local_output_buf_V_d1 => grp_DPEComputation_Pipeline_VITIS_LOOP_296_3_fu_73_local_output_buf_V_d1,
        local_output_buf_V_q1 => local_output_buf_V_q1);

    grp_DPEComputation_Pipeline_VITIS_LOOP_303_4_fu_84 : component LINEAR_DPEComputation_Pipeline_VITIS_LOOP_303_4
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_DPEComputation_Pipeline_VITIS_LOOP_303_4_fu_84_ap_start,
        ap_done => grp_DPEComputation_Pipeline_VITIS_LOOP_303_4_fu_84_ap_done,
        ap_idle => grp_DPEComputation_Pipeline_VITIS_LOOP_303_4_fu_84_ap_idle,
        ap_ready => grp_DPEComputation_Pipeline_VITIS_LOOP_303_4_fu_84_ap_ready,
        add_ln305 => add_ln305_reg_165,
        buffer_out_address0 => grp_DPEComputation_Pipeline_VITIS_LOOP_303_4_fu_84_buffer_out_address0,
        buffer_out_ce0 => grp_DPEComputation_Pipeline_VITIS_LOOP_303_4_fu_84_buffer_out_ce0,
        buffer_out_we0 => grp_DPEComputation_Pipeline_VITIS_LOOP_303_4_fu_84_buffer_out_we0,
        buffer_out_d0 => grp_DPEComputation_Pipeline_VITIS_LOOP_303_4_fu_84_buffer_out_d0,
        local_output_buf_V_address0 => grp_DPEComputation_Pipeline_VITIS_LOOP_303_4_fu_84_local_output_buf_V_address0,
        local_output_buf_V_ce0 => grp_DPEComputation_Pipeline_VITIS_LOOP_303_4_fu_84_local_output_buf_V_ce0,
        local_output_buf_V_q0 => local_output_buf_V_q0);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_DPEComputation_Pipeline_VITIS_LOOP_287_1_fu_67_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_DPEComputation_Pipeline_VITIS_LOOP_287_1_fu_67_ap_start_reg <= ap_const_logic_0;
            else
                if (((icmp_ln286_fu_92_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    grp_DPEComputation_Pipeline_VITIS_LOOP_287_1_fu_67_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_DPEComputation_Pipeline_VITIS_LOOP_287_1_fu_67_ap_ready = ap_const_logic_1)) then 
                    grp_DPEComputation_Pipeline_VITIS_LOOP_287_1_fu_67_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_DPEComputation_Pipeline_VITIS_LOOP_291_2_fu_58_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_DPEComputation_Pipeline_VITIS_LOOP_291_2_fu_58_ap_start_reg <= ap_const_logic_0;
            else
                if (((icmp_ln286_fu_92_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    grp_DPEComputation_Pipeline_VITIS_LOOP_291_2_fu_58_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_DPEComputation_Pipeline_VITIS_LOOP_291_2_fu_58_ap_ready = ap_const_logic_1)) then 
                    grp_DPEComputation_Pipeline_VITIS_LOOP_291_2_fu_58_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_DPEComputation_Pipeline_VITIS_LOOP_296_3_fu_73_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_DPEComputation_Pipeline_VITIS_LOOP_296_3_fu_73_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_DPEComputation_Pipeline_VITIS_LOOP_296_3_fu_73_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_DPEComputation_Pipeline_VITIS_LOOP_296_3_fu_73_ap_ready = ap_const_logic_1)) then 
                    grp_DPEComputation_Pipeline_VITIS_LOOP_296_3_fu_73_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_DPEComputation_Pipeline_VITIS_LOOP_303_4_fu_84_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_DPEComputation_Pipeline_VITIS_LOOP_303_4_fu_84_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                    grp_DPEComputation_Pipeline_VITIS_LOOP_303_4_fu_84_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_DPEComputation_Pipeline_VITIS_LOOP_303_4_fu_84_ap_ready = ap_const_logic_1)) then 
                    grp_DPEComputation_Pipeline_VITIS_LOOP_303_4_fu_84_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln286_fu_92_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    add_ln292_reg_160(9 downto 2) <= add_ln292_fu_118_p2(9 downto 2);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                    add_ln305_reg_165(9 downto 2) <= add_ln305_fu_143_p2(9 downto 2);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                icmp_ln286_reg_156 <= icmp_ln286_fu_92_p2;
            end if;
        end if;
    end process;
    add_ln292_reg_160(1 downto 0) <= "00";
    add_ln305_reg_165(1 downto 0) <= "00";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_DPEComputation_Pipeline_VITIS_LOOP_296_3_fu_73_ap_done, grp_DPEComputation_Pipeline_VITIS_LOOP_303_4_fu_84_ap_done, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state6, ap_block_state2_on_subcall_done)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_boolean_0 = ap_block_state2_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_DPEComputation_Pipeline_VITIS_LOOP_296_3_fu_73_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_DPEComputation_Pipeline_VITIS_LOOP_303_4_fu_84_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;
    IACT_TEMP_BUFFER_address0 <= grp_DPEComputation_Pipeline_VITIS_LOOP_296_3_fu_73_IACT_TEMP_BUFFER_address0;
    IACT_TEMP_BUFFER_ce0 <= grp_DPEComputation_Pipeline_VITIS_LOOP_296_3_fu_73_IACT_TEMP_BUFFER_ce0;
    add_ln292_fu_118_p2 <= std_logic_vector(unsigned(tmp_fu_98_p3) + unsigned(zext_ln292_fu_114_p1));
    add_ln305_fu_143_p2 <= std_logic_vector(unsigned(tmp_11_fu_125_p3) + unsigned(zext_ln305_fu_139_p1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(ap_block_state2_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state2_on_subcall_done)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_DPEComputation_Pipeline_VITIS_LOOP_296_3_fu_73_ap_done)
    begin
        if ((grp_DPEComputation_Pipeline_VITIS_LOOP_296_3_fu_73_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_ST_fsm_state6_blk_assign_proc : process(grp_DPEComputation_Pipeline_VITIS_LOOP_303_4_fu_84_ap_done)
    begin
        if ((grp_DPEComputation_Pipeline_VITIS_LOOP_303_4_fu_84_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state2_on_subcall_done_assign_proc : process(icmp_ln286_reg_156, grp_DPEComputation_Pipeline_VITIS_LOOP_291_2_fu_58_ap_done, grp_DPEComputation_Pipeline_VITIS_LOOP_287_1_fu_67_ap_done)
    begin
                ap_block_state2_on_subcall_done <= (((grp_DPEComputation_Pipeline_VITIS_LOOP_291_2_fu_58_ap_done = ap_const_logic_0) and (icmp_ln286_reg_156 = ap_const_lv1_0)) or ((icmp_ln286_reg_156 = ap_const_lv1_1) and (grp_DPEComputation_Pipeline_VITIS_LOOP_287_1_fu_67_ap_done = ap_const_logic_0)));
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, grp_DPEComputation_Pipeline_VITIS_LOOP_303_4_fu_84_ap_done, ap_CS_fsm_state6)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)) or ((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_DPEComputation_Pipeline_VITIS_LOOP_303_4_fu_84_ap_done = ap_const_logic_1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_DPEComputation_Pipeline_VITIS_LOOP_303_4_fu_84_ap_done, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_DPEComputation_Pipeline_VITIS_LOOP_303_4_fu_84_ap_done = ap_const_logic_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    bit_buffer_weights_address0 <= grp_DPEComputation_Pipeline_VITIS_LOOP_296_3_fu_73_bit_buffer_weights_address0;
    bit_buffer_weights_ce0 <= grp_DPEComputation_Pipeline_VITIS_LOOP_296_3_fu_73_bit_buffer_weights_ce0;

    buffer_out_address0_assign_proc : process(icmp_ln286_reg_156, grp_DPEComputation_Pipeline_VITIS_LOOP_291_2_fu_58_buffer_out_address0, grp_DPEComputation_Pipeline_VITIS_LOOP_303_4_fu_84_buffer_out_address0, ap_CS_fsm_state2, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            buffer_out_address0 <= grp_DPEComputation_Pipeline_VITIS_LOOP_303_4_fu_84_buffer_out_address0;
        elsif (((icmp_ln286_reg_156 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            buffer_out_address0 <= grp_DPEComputation_Pipeline_VITIS_LOOP_291_2_fu_58_buffer_out_address0;
        else 
            buffer_out_address0 <= "XXXXXXXXXX";
        end if; 
    end process;


    buffer_out_ce0_assign_proc : process(icmp_ln286_reg_156, grp_DPEComputation_Pipeline_VITIS_LOOP_291_2_fu_58_buffer_out_ce0, grp_DPEComputation_Pipeline_VITIS_LOOP_303_4_fu_84_buffer_out_ce0, ap_CS_fsm_state2, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            buffer_out_ce0 <= grp_DPEComputation_Pipeline_VITIS_LOOP_303_4_fu_84_buffer_out_ce0;
        elsif (((icmp_ln286_reg_156 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            buffer_out_ce0 <= grp_DPEComputation_Pipeline_VITIS_LOOP_291_2_fu_58_buffer_out_ce0;
        else 
            buffer_out_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    buffer_out_d0 <= grp_DPEComputation_Pipeline_VITIS_LOOP_303_4_fu_84_buffer_out_d0;

    buffer_out_we0_assign_proc : process(grp_DPEComputation_Pipeline_VITIS_LOOP_303_4_fu_84_buffer_out_we0, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            buffer_out_we0 <= grp_DPEComputation_Pipeline_VITIS_LOOP_303_4_fu_84_buffer_out_we0;
        else 
            buffer_out_we0 <= ap_const_logic_0;
        end if; 
    end process;

    grp_DPEComputation_Pipeline_VITIS_LOOP_287_1_fu_67_ap_start <= grp_DPEComputation_Pipeline_VITIS_LOOP_287_1_fu_67_ap_start_reg;
    grp_DPEComputation_Pipeline_VITIS_LOOP_291_2_fu_58_ap_start <= grp_DPEComputation_Pipeline_VITIS_LOOP_291_2_fu_58_ap_start_reg;
    grp_DPEComputation_Pipeline_VITIS_LOOP_296_3_fu_73_ap_start <= grp_DPEComputation_Pipeline_VITIS_LOOP_296_3_fu_73_ap_start_reg;
    grp_DPEComputation_Pipeline_VITIS_LOOP_303_4_fu_84_ap_start <= grp_DPEComputation_Pipeline_VITIS_LOOP_303_4_fu_84_ap_start_reg;
    icmp_ln286_fu_92_p2 <= "1" when (block_idx_x = ap_const_lv27_0) else "0";

    local_output_buf_V_address0_assign_proc : process(icmp_ln286_reg_156, grp_DPEComputation_Pipeline_VITIS_LOOP_291_2_fu_58_local_output_buf_V_address0, grp_DPEComputation_Pipeline_VITIS_LOOP_287_1_fu_67_local_output_buf_V_address0, grp_DPEComputation_Pipeline_VITIS_LOOP_296_3_fu_73_local_output_buf_V_address0, grp_DPEComputation_Pipeline_VITIS_LOOP_303_4_fu_84_local_output_buf_V_address0, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            local_output_buf_V_address0 <= grp_DPEComputation_Pipeline_VITIS_LOOP_303_4_fu_84_local_output_buf_V_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            local_output_buf_V_address0 <= grp_DPEComputation_Pipeline_VITIS_LOOP_296_3_fu_73_local_output_buf_V_address0;
        elsif (((icmp_ln286_reg_156 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            local_output_buf_V_address0 <= grp_DPEComputation_Pipeline_VITIS_LOOP_287_1_fu_67_local_output_buf_V_address0;
        elsif (((icmp_ln286_reg_156 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            local_output_buf_V_address0 <= grp_DPEComputation_Pipeline_VITIS_LOOP_291_2_fu_58_local_output_buf_V_address0;
        else 
            local_output_buf_V_address0 <= "XXXXXXXXXX";
        end if; 
    end process;


    local_output_buf_V_ce0_assign_proc : process(icmp_ln286_reg_156, grp_DPEComputation_Pipeline_VITIS_LOOP_291_2_fu_58_local_output_buf_V_ce0, grp_DPEComputation_Pipeline_VITIS_LOOP_287_1_fu_67_local_output_buf_V_ce0, grp_DPEComputation_Pipeline_VITIS_LOOP_296_3_fu_73_local_output_buf_V_ce0, grp_DPEComputation_Pipeline_VITIS_LOOP_303_4_fu_84_local_output_buf_V_ce0, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            local_output_buf_V_ce0 <= grp_DPEComputation_Pipeline_VITIS_LOOP_303_4_fu_84_local_output_buf_V_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            local_output_buf_V_ce0 <= grp_DPEComputation_Pipeline_VITIS_LOOP_296_3_fu_73_local_output_buf_V_ce0;
        elsif (((icmp_ln286_reg_156 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            local_output_buf_V_ce0 <= grp_DPEComputation_Pipeline_VITIS_LOOP_287_1_fu_67_local_output_buf_V_ce0;
        elsif (((icmp_ln286_reg_156 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            local_output_buf_V_ce0 <= grp_DPEComputation_Pipeline_VITIS_LOOP_291_2_fu_58_local_output_buf_V_ce0;
        else 
            local_output_buf_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    local_output_buf_V_ce1_assign_proc : process(grp_DPEComputation_Pipeline_VITIS_LOOP_296_3_fu_73_local_output_buf_V_ce1, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            local_output_buf_V_ce1 <= grp_DPEComputation_Pipeline_VITIS_LOOP_296_3_fu_73_local_output_buf_V_ce1;
        else 
            local_output_buf_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    local_output_buf_V_d0_assign_proc : process(icmp_ln286_reg_156, grp_DPEComputation_Pipeline_VITIS_LOOP_291_2_fu_58_local_output_buf_V_d0, grp_DPEComputation_Pipeline_VITIS_LOOP_287_1_fu_67_local_output_buf_V_d0, grp_DPEComputation_Pipeline_VITIS_LOOP_296_3_fu_73_local_output_buf_V_d0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            local_output_buf_V_d0 <= grp_DPEComputation_Pipeline_VITIS_LOOP_296_3_fu_73_local_output_buf_V_d0;
        elsif (((icmp_ln286_reg_156 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            local_output_buf_V_d0 <= grp_DPEComputation_Pipeline_VITIS_LOOP_287_1_fu_67_local_output_buf_V_d0;
        elsif (((icmp_ln286_reg_156 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            local_output_buf_V_d0 <= grp_DPEComputation_Pipeline_VITIS_LOOP_291_2_fu_58_local_output_buf_V_d0;
        else 
            local_output_buf_V_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    local_output_buf_V_we0_assign_proc : process(icmp_ln286_reg_156, grp_DPEComputation_Pipeline_VITIS_LOOP_291_2_fu_58_local_output_buf_V_we0, grp_DPEComputation_Pipeline_VITIS_LOOP_287_1_fu_67_local_output_buf_V_we0, grp_DPEComputation_Pipeline_VITIS_LOOP_296_3_fu_73_local_output_buf_V_we0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            local_output_buf_V_we0 <= grp_DPEComputation_Pipeline_VITIS_LOOP_296_3_fu_73_local_output_buf_V_we0;
        elsif (((icmp_ln286_reg_156 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            local_output_buf_V_we0 <= grp_DPEComputation_Pipeline_VITIS_LOOP_287_1_fu_67_local_output_buf_V_we0;
        elsif (((icmp_ln286_reg_156 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            local_output_buf_V_we0 <= grp_DPEComputation_Pipeline_VITIS_LOOP_291_2_fu_58_local_output_buf_V_we0;
        else 
            local_output_buf_V_we0 <= ap_const_logic_0;
        end if; 
    end process;


    local_output_buf_V_we1_assign_proc : process(grp_DPEComputation_Pipeline_VITIS_LOOP_296_3_fu_73_local_output_buf_V_we1, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            local_output_buf_V_we1 <= grp_DPEComputation_Pipeline_VITIS_LOOP_296_3_fu_73_local_output_buf_V_we1;
        else 
            local_output_buf_V_we1 <= ap_const_logic_0;
        end if; 
    end process;

    processing_buffer_address0 <= grp_DPEComputation_Pipeline_VITIS_LOOP_296_3_fu_73_processing_buffer_address0;
    processing_buffer_ce0 <= grp_DPEComputation_Pipeline_VITIS_LOOP_296_3_fu_73_processing_buffer_ce0;
    tmp_11_fu_125_p3 <= (block_idx_y & ap_const_lv4_0);
    tmp_12_fu_132_p3 <= (block_idx_y & ap_const_lv2_0);
    tmp_fu_98_p3 <= (block_idx_y & ap_const_lv4_0);
    tmp_s_fu_106_p3 <= (block_idx_y & ap_const_lv2_0);
    zext_ln292_fu_114_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_106_p3),10));
    zext_ln305_fu_139_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_12_fu_132_p3),10));
end behav;
