set SynModuleInfo {
  {SRCNAME entry_proc MODELNAME entry_proc RTLNAME LINEAR_entry_proc}
  {SRCNAME Block_.split10_proc MODELNAME Block_split10_proc RTLNAME LINEAR_Block_split10_proc
    SUBMODULES {
      {MODELNAME LINEAR_mul_32s_34ns_65_1_1 RTLNAME LINEAR_mul_32s_34ns_65_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME ReadFromMem_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_32_2 MODELNAME ReadFromMem_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_32_2 RTLNAME LINEAR_ReadFromMem_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_32_2
    SUBMODULES {
      {MODELNAME LINEAR_urem_32ns_8ns_7_36_1 RTLNAME LINEAR_urem_32ns_8ns_7_36_1 BINDTYPE op TYPE urem IMPL auto LATENCY 35 ALLOW_PRAGMA 1}
      {MODELNAME LINEAR_mul_32ns_34ns_65_1_1 RTLNAME LINEAR_mul_32ns_34ns_65_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME LINEAR_mul_64ns_66ns_129_1_1 RTLNAME LINEAR_mul_64ns_66ns_129_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME LINEAR_flow_control_loop_pipe_sequential_init RTLNAME LINEAR_flow_control_loop_pipe_sequential_init BINDTYPE interface TYPE internal_upc_flow_control INSTNAME LINEAR_flow_control_loop_pipe_sequential_init_U}
    }
  }
  {SRCNAME ReadFromMem_Pipeline_VITIS_LOOP_153_8 MODELNAME ReadFromMem_Pipeline_VITIS_LOOP_153_8 RTLNAME LINEAR_ReadFromMem_Pipeline_VITIS_LOOP_153_8}
  {SRCNAME ReadFromMem_Pipeline_VITIS_LOOP_168_11_VITIS_LOOP_177_13 MODELNAME ReadFromMem_Pipeline_VITIS_LOOP_168_11_VITIS_LOOP_177_13 RTLNAME LINEAR_ReadFromMem_Pipeline_VITIS_LOOP_168_11_VITIS_LOOP_177_13}
  {SRCNAME ReadFromMem_Pipeline_VITIS_LOOP_187_14_VITIS_LOOP_189_15_VITIS_LOOP_192_16 MODELNAME ReadFromMem_Pipeline_VITIS_LOOP_187_14_VITIS_LOOP_189_15_VITIS_LOOP_192_16 RTLNAME LINEAR_ReadFromMem_Pipeline_VITIS_LOOP_187_14_VITIS_LOOP_189_15_VITIS_LOOP_192_16
    SUBMODULES {
      {MODELNAME LINEAR_mul_29s_27ns_29_1_1 RTLNAME LINEAR_mul_29s_27ns_29_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME LINEAR_urem_10ns_5ns_4_14_1 RTLNAME LINEAR_urem_10ns_5ns_4_14_1 BINDTYPE op TYPE urem IMPL auto LATENCY 13 ALLOW_PRAGMA 1}
      {MODELNAME LINEAR_mul_mul_10ns_11ns_21_4_1 RTLNAME LINEAR_mul_mul_10ns_11ns_21_4_1 BINDTYPE op TYPE mul IMPL dsp LATENCY 3 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME ReadFromMem_Pipeline_VITIS_LOOP_216_18 MODELNAME ReadFromMem_Pipeline_VITIS_LOOP_216_18 RTLNAME LINEAR_ReadFromMem_Pipeline_VITIS_LOOP_216_18}
  {SRCNAME ReadFromMem MODELNAME ReadFromMem RTLNAME LINEAR_ReadFromMem
    SUBMODULES {
      {MODELNAME LINEAR_mul_32s_32s_32_1_1 RTLNAME LINEAR_mul_32s_32s_32_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME LINEAR_mul_64ns_5ns_68_1_1 RTLNAME LINEAR_mul_64ns_5ns_68_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME LINEAR_mul_32ns_32ns_64_1_1 RTLNAME LINEAR_mul_32ns_32ns_64_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME LINEAR_mul_28ns_33ns_61_1_1 RTLNAME LINEAR_mul_28ns_33ns_61_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME CreateBitMask_Pipeline_VITIS_LOOP_230_2 MODELNAME CreateBitMask_Pipeline_VITIS_LOOP_230_2 RTLNAME LINEAR_CreateBitMask_Pipeline_VITIS_LOOP_230_2}
  {SRCNAME CreateBitMask_Pipeline_VITIS_LOOP_237_3_VITIS_LOOP_241_4 MODELNAME CreateBitMask_Pipeline_VITIS_LOOP_237_3_VITIS_LOOP_241_4 RTLNAME LINEAR_CreateBitMask_Pipeline_VITIS_LOOP_237_3_VITIS_LOOP_241_4}
  {SRCNAME CreateBitMask MODELNAME CreateBitMask RTLNAME LINEAR_CreateBitMask}
  {SRCNAME RunDataFlow_Pipeline_VITIS_LOOP_341_1 MODELNAME RunDataFlow_Pipeline_VITIS_LOOP_341_1 RTLNAME LINEAR_RunDataFlow_Pipeline_VITIS_LOOP_341_1}
  {SRCNAME DPEComputation_Pipeline_VITIS_LOOP_291_2 MODELNAME DPEComputation_Pipeline_VITIS_LOOP_291_2 RTLNAME LINEAR_DPEComputation_Pipeline_VITIS_LOOP_291_2}
  {SRCNAME DPEComputation_Pipeline_VITIS_LOOP_287_1 MODELNAME DPEComputation_Pipeline_VITIS_LOOP_287_1 RTLNAME LINEAR_DPEComputation_Pipeline_VITIS_LOOP_287_1}
  {SRCNAME DPEUnit MODELNAME DPEUnit RTLNAME LINEAR_DPEUnit
    SUBMODULES {
      {MODELNAME LINEAR_mul_32s_32s_56_1_1 RTLNAME LINEAR_mul_32s_32s_56_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME DPEComputation_Pipeline_VITIS_LOOP_296_3 MODELNAME DPEComputation_Pipeline_VITIS_LOOP_296_3 RTLNAME LINEAR_DPEComputation_Pipeline_VITIS_LOOP_296_3}
  {SRCNAME DPEComputation_Pipeline_VITIS_LOOP_303_4 MODELNAME DPEComputation_Pipeline_VITIS_LOOP_303_4 RTLNAME LINEAR_DPEComputation_Pipeline_VITIS_LOOP_303_4}
  {SRCNAME DPEComputation MODELNAME DPEComputation RTLNAME LINEAR_DPEComputation
    SUBMODULES {
      {MODELNAME LINEAR_DPEComputation_local_output_buf_V RTLNAME LINEAR_DPEComputation_local_output_buf_V BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME RunDataFlow MODELNAME RunDataFlow RTLNAME LINEAR_RunDataFlow
    SUBMODULES {
      {MODELNAME LINEAR_mul_28s_28s_32_1_1 RTLNAME LINEAR_mul_28s_28s_32_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME LINEAR_RunDataFlow_IACT_TEMP_BUFFER_V RTLNAME LINEAR_RunDataFlow_IACT_TEMP_BUFFER_V BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME LINEAR_RunDataFlow_first_processing_buffer_V RTLNAME LINEAR_RunDataFlow_first_processing_buffer_V BINDTYPE storage TYPE ram_t2p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME LINEAR_RunDataFlow_first_bit_buffer_weights_V RTLNAME LINEAR_RunDataFlow_first_bit_buffer_weights_V BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME OutputBuffer_Pipeline_VITIS_LOOP_329_1 MODELNAME OutputBuffer_Pipeline_VITIS_LOOP_329_1 RTLNAME LINEAR_OutputBuffer_Pipeline_VITIS_LOOP_329_1}
  {SRCNAME OutputBuffer MODELNAME OutputBuffer RTLNAME LINEAR_OutputBuffer}
  {SRCNAME LINEAR MODELNAME LINEAR RTLNAME LINEAR IS_TOP 1
    SUBMODULES {
      {MODELNAME LINEAR_weight_buffer_V_0 RTLNAME LINEAR_weight_buffer_V_0 BINDTYPE storage TYPE ram_t2p IMPL uram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME LINEAR_weight_buffer_V_5 RTLNAME LINEAR_weight_buffer_V_5 BINDTYPE storage TYPE ram_t2p IMPL uram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME LINEAR_iact_buffer_V RTLNAME LINEAR_iact_buffer_V BINDTYPE storage TYPE ram_t2p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME LINEAR_output_buf_V_memcore RTLNAME LINEAR_output_buf_V_memcore BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME LINEAR_output_buf_V RTLNAME LINEAR_output_buf_V BINDTYPE storage TYPE ram IMPL auto LATENCY 2}
      {MODELNAME LINEAR_fifo_w64_d3_S RTLNAME LINEAR_fifo_w64_d3_S BINDTYPE storage TYPE fifo IMPL srl LATENCY -1 ALLOW_PRAGMA 1 INSTNAME {$InstName}}
      {MODELNAME LINEAR_fifo_w28_d2_S RTLNAME LINEAR_fifo_w28_d2_S BINDTYPE storage TYPE fifo IMPL srl LATENCY -1 ALLOW_PRAGMA 1 INSTNAME {$InstName}}
      {MODELNAME LINEAR_fifo_w32_d100_A RTLNAME LINEAR_fifo_w32_d100_A BINDTYPE storage TYPE fifo IMPL memory LATENCY -1 ALLOW_PRAGMA 1 INSTNAME {$InstName}}
      {MODELNAME LINEAR_fifo_w32_d32_S RTLNAME LINEAR_fifo_w32_d32_S BINDTYPE storage TYPE fifo IMPL srl LATENCY -1 ALLOW_PRAGMA 1 INSTNAME {$InstName}}
      {MODELNAME LINEAR_fifo_w32_d3_S RTLNAME LINEAR_fifo_w32_d3_S BINDTYPE storage TYPE fifo IMPL srl LATENCY -1 ALLOW_PRAGMA 1 INSTNAME {$InstName}}
      {MODELNAME LINEAR_control_s_axi RTLNAME LINEAR_control_s_axi BINDTYPE interface TYPE interface_s_axilite}
      {MODELNAME LINEAR_ifc1_m_axi RTLNAME LINEAR_ifc1_m_axi BINDTYPE interface TYPE interface_m_axi}
      {MODELNAME LINEAR_ifc2_m_axi RTLNAME LINEAR_ifc2_m_axi BINDTYPE interface TYPE interface_m_axi}
      {MODELNAME LINEAR_ifc3_m_axi RTLNAME LINEAR_ifc3_m_axi BINDTYPE interface TYPE interface_m_axi}
      {MODELNAME LINEAR_ifc4_m_axi RTLNAME LINEAR_ifc4_m_axi BINDTYPE interface TYPE interface_m_axi}
      {MODELNAME LINEAR_ifc5_m_axi RTLNAME LINEAR_ifc5_m_axi BINDTYPE interface TYPE interface_m_axi}
      {MODELNAME LINEAR_ifc6_m_axi RTLNAME LINEAR_ifc6_m_axi BINDTYPE interface TYPE interface_m_axi}
    }
  }
}
